// Code generated by go-swagger; DO NOT EDIT.

package nunc_connections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams creates a new DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams() *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	return &DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParamsWithTimeout creates a new DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams object
// with the ability to set a timeout on a request.
func NewDeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParamsWithTimeout(timeout time.Duration) *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	return &DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams{
		timeout: timeout,
	}
}

// NewDeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParamsWithContext creates a new DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams object
// with the ability to set a context for a request.
func NewDeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParamsWithContext(ctx context.Context) *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	return &DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams{
		Context: ctx,
	}
}

// NewDeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParamsWithHTTPClient creates a new DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParamsWithHTTPClient(client *http.Client) *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	return &DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams{
		HTTPClient: client,
	}
}

/*
DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams contains all the parameters to send to the API endpoint

	for the delete v1 nunc connections nunc connection Id links link Id operation.

	Typically these are written to a http.Request.
*/
type DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams struct {

	// LinkID.
	LinkID string

	// NuncConnectionID.
	//
	// Format: int32
	NuncConnectionID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete v1 nunc connections nunc connection Id links link Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) WithDefaults() *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete v1 nunc connections nunc connection Id links link Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) WithTimeout(timeout time.Duration) *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) WithContext(ctx context.Context) *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) WithHTTPClient(client *http.Client) *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLinkID adds the linkID to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) WithLinkID(linkID string) *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	o.SetLinkID(linkID)
	return o
}

// SetLinkID adds the linkId to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) SetLinkID(linkID string) {
	o.LinkID = linkID
}

// WithNuncConnectionID adds the nuncConnectionID to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) WithNuncConnectionID(nuncConnectionID int32) *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams {
	o.SetNuncConnectionID(nuncConnectionID)
	return o
}

// SetNuncConnectionID adds the nuncConnectionId to the delete v1 nunc connections nunc connection Id links link Id params
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) SetNuncConnectionID(nuncConnectionID int32) {
	o.NuncConnectionID = nuncConnectionID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteV1NuncConnectionsNuncConnectionIDLinksLinkIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param link_id
	if err := r.SetPathParam("link_id", o.LinkID); err != nil {
		return err
	}

	// path param nunc_connection_id
	if err := r.SetPathParam("nunc_connection_id", swag.FormatInt32(o.NuncConnectionID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
