// Code generated by go-swagger; DO NOT EDIT.

package audiences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCreateAudienceParams creates a new CreateAudienceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAudienceParams() *CreateAudienceParams {
	return &CreateAudienceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAudienceParamsWithTimeout creates a new CreateAudienceParams object
// with the ability to set a timeout on a request.
func NewCreateAudienceParamsWithTimeout(timeout time.Duration) *CreateAudienceParams {
	return &CreateAudienceParams{
		timeout: timeout,
	}
}

// NewCreateAudienceParamsWithContext creates a new CreateAudienceParams object
// with the ability to set a context for a request.
func NewCreateAudienceParamsWithContext(ctx context.Context) *CreateAudienceParams {
	return &CreateAudienceParams{
		Context: ctx,
	}
}

// NewCreateAudienceParamsWithHTTPClient creates a new CreateAudienceParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAudienceParamsWithHTTPClient(client *http.Client) *CreateAudienceParams {
	return &CreateAudienceParams{
		HTTPClient: client,
	}
}

/*
CreateAudienceParams contains all the parameters to send to the API endpoint

	for the create audience operation.

	Typically these are written to a http.Request.
*/
type CreateAudienceParams struct {

	/* Default.

	   Whether this is the default audience
	*/
	Default *bool

	/* Description.

	   Description of the audience (max 4000 characters)
	*/
	Description string

	/* DetailsPrompt.

	   The prompt to display when collecting this detail
	*/
	DetailsPrompt []string

	/* DetailsQuestion.

	   The incident detail question (max 255 characters)
	*/
	DetailsQuestion []string

	/* DetailsSlug.

	   Optional unique identifier for this detail
	*/
	DetailsSlug []string

	/* Name.

	   Name of the audience (max 255 characters)
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create audience params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAudienceParams) WithDefaults() *CreateAudienceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create audience params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAudienceParams) SetDefaults() {
	var (
		defaultVarDefault = bool(false)
	)

	val := CreateAudienceParams{
		Default: &defaultVarDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create audience params
func (o *CreateAudienceParams) WithTimeout(timeout time.Duration) *CreateAudienceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create audience params
func (o *CreateAudienceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create audience params
func (o *CreateAudienceParams) WithContext(ctx context.Context) *CreateAudienceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create audience params
func (o *CreateAudienceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create audience params
func (o *CreateAudienceParams) WithHTTPClient(client *http.Client) *CreateAudienceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create audience params
func (o *CreateAudienceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDefault adds the defaultVar to the create audience params
func (o *CreateAudienceParams) WithDefault(defaultVar *bool) *CreateAudienceParams {
	o.SetDefault(defaultVar)
	return o
}

// SetDefault adds the default to the create audience params
func (o *CreateAudienceParams) SetDefault(defaultVar *bool) {
	o.Default = defaultVar
}

// WithDescription adds the description to the create audience params
func (o *CreateAudienceParams) WithDescription(description string) *CreateAudienceParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the create audience params
func (o *CreateAudienceParams) SetDescription(description string) {
	o.Description = description
}

// WithDetailsPrompt adds the detailsPrompt to the create audience params
func (o *CreateAudienceParams) WithDetailsPrompt(detailsPrompt []string) *CreateAudienceParams {
	o.SetDetailsPrompt(detailsPrompt)
	return o
}

// SetDetailsPrompt adds the detailsPrompt to the create audience params
func (o *CreateAudienceParams) SetDetailsPrompt(detailsPrompt []string) {
	o.DetailsPrompt = detailsPrompt
}

// WithDetailsQuestion adds the detailsQuestion to the create audience params
func (o *CreateAudienceParams) WithDetailsQuestion(detailsQuestion []string) *CreateAudienceParams {
	o.SetDetailsQuestion(detailsQuestion)
	return o
}

// SetDetailsQuestion adds the detailsQuestion to the create audience params
func (o *CreateAudienceParams) SetDetailsQuestion(detailsQuestion []string) {
	o.DetailsQuestion = detailsQuestion
}

// WithDetailsSlug adds the detailsSlug to the create audience params
func (o *CreateAudienceParams) WithDetailsSlug(detailsSlug []string) *CreateAudienceParams {
	o.SetDetailsSlug(detailsSlug)
	return o
}

// SetDetailsSlug adds the detailsSlug to the create audience params
func (o *CreateAudienceParams) SetDetailsSlug(detailsSlug []string) {
	o.DetailsSlug = detailsSlug
}

// WithName adds the name to the create audience params
func (o *CreateAudienceParams) WithName(name string) *CreateAudienceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the create audience params
func (o *CreateAudienceParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAudienceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Default != nil {

		// form param default
		var frDefault bool
		if o.Default != nil {
			frDefault = *o.Default
		}
		fDefault := swag.FormatBool(frDefault)
		if fDefault != "" {
			if err := r.SetFormParam("default", fDefault); err != nil {
				return err
			}
		}
	}

	// form param description
	frDescription := o.Description
	fDescription := frDescription
	if fDescription != "" {
		if err := r.SetFormParam("description", fDescription); err != nil {
			return err
		}
	}

	if o.DetailsPrompt != nil {

		// binding items for details[prompt]
		joinedDetailsPrompt := o.bindParamDetailsPrompt(reg)

		// form array param details[prompt]
		if err := r.SetFormParam("details[prompt]", joinedDetailsPrompt...); err != nil {
			return err
		}
	}

	if o.DetailsQuestion != nil {

		// binding items for details[question]
		joinedDetailsQuestion := o.bindParamDetailsQuestion(reg)

		// form array param details[question]
		if err := r.SetFormParam("details[question]", joinedDetailsQuestion...); err != nil {
			return err
		}
	}

	if o.DetailsSlug != nil {

		// binding items for details[slug]
		joinedDetailsSlug := o.bindParamDetailsSlug(reg)

		// form array param details[slug]
		if err := r.SetFormParam("details[slug]", joinedDetailsSlug...); err != nil {
			return err
		}
	}

	// form param name
	frName := o.Name
	fName := frName
	if fName != "" {
		if err := r.SetFormParam("name", fName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamCreateAudience binds the parameter details[prompt]
func (o *CreateAudienceParams) bindParamDetailsPrompt(formats strfmt.Registry) []string {
	detailsPromptIR := o.DetailsPrompt

	var detailsPromptIC []string
	for _, detailsPromptIIR := range detailsPromptIR { // explode []string

		detailsPromptIIV := detailsPromptIIR // string as string
		detailsPromptIC = append(detailsPromptIC, detailsPromptIIV)
	}

	// items.CollectionFormat: ""
	detailsPromptIS := swag.JoinByFormat(detailsPromptIC, "")

	return detailsPromptIS
}

// bindParamCreateAudience binds the parameter details[question]
func (o *CreateAudienceParams) bindParamDetailsQuestion(formats strfmt.Registry) []string {
	detailsQuestionIR := o.DetailsQuestion

	var detailsQuestionIC []string
	for _, detailsQuestionIIR := range detailsQuestionIR { // explode []string

		detailsQuestionIIV := detailsQuestionIIR // string as string
		detailsQuestionIC = append(detailsQuestionIC, detailsQuestionIIV)
	}

	// items.CollectionFormat: ""
	detailsQuestionIS := swag.JoinByFormat(detailsQuestionIC, "")

	return detailsQuestionIS
}

// bindParamCreateAudience binds the parameter details[slug]
func (o *CreateAudienceParams) bindParamDetailsSlug(formats strfmt.Registry) []string {
	detailsSlugIR := o.DetailsSlug

	var detailsSlugIC []string
	for _, detailsSlugIIR := range detailsSlugIR { // explode []string

		detailsSlugIIV := detailsSlugIIR // string as string
		detailsSlugIC = append(detailsSlugIC, detailsSlugIIV)
	}

	// items.CollectionFormat: ""
	detailsSlugIS := swag.JoinByFormat(detailsSlugIC, "")

	return detailsSlugIS
}
