// Code generated by go-swagger; DO NOT EDIT.

package audiences

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// GetV1AudiencesMemberMemberIDDefaultReader is a Reader for the GetV1AudiencesMemberMemberIDDefault structure.
type GetV1AudiencesMemberMemberIDDefaultReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1AudiencesMemberMemberIDDefaultReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1AudiencesMemberMemberIDDefaultOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetV1AudiencesMemberMemberIDDefaultOK creates a GetV1AudiencesMemberMemberIDDefaultOK with default headers values
func NewGetV1AudiencesMemberMemberIDDefaultOK() *GetV1AudiencesMemberMemberIDDefaultOK {
	return &GetV1AudiencesMemberMemberIDDefaultOK{}
}

/*
GetV1AudiencesMemberMemberIDDefaultOK describes a response with status code 200, with default header values.

Get member's default audience
*/
type GetV1AudiencesMemberMemberIDDefaultOK struct {
	Payload *models.AudiencesEntitiesAudienceEntity
}

// IsSuccess returns true when this get v1 audiences member member Id default o k response has a 2xx status code
func (o *GetV1AudiencesMemberMemberIDDefaultOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 audiences member member Id default o k response has a 3xx status code
func (o *GetV1AudiencesMemberMemberIDDefaultOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 audiences member member Id default o k response has a 4xx status code
func (o *GetV1AudiencesMemberMemberIDDefaultOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 audiences member member Id default o k response has a 5xx status code
func (o *GetV1AudiencesMemberMemberIDDefaultOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 audiences member member Id default o k response a status code equal to that given
func (o *GetV1AudiencesMemberMemberIDDefaultOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetV1AudiencesMemberMemberIDDefaultOK) Error() string {
	return fmt.Sprintf("[GET /v1/audiences/member/{member_id}/default][%d] getV1AudiencesMemberMemberIdDefaultOK  %+v", 200, o.Payload)
}

func (o *GetV1AudiencesMemberMemberIDDefaultOK) String() string {
	return fmt.Sprintf("[GET /v1/audiences/member/{member_id}/default][%d] getV1AudiencesMemberMemberIdDefaultOK  %+v", 200, o.Payload)
}

func (o *GetV1AudiencesMemberMemberIDDefaultOK) GetPayload() *models.AudiencesEntitiesAudienceEntity {
	return o.Payload
}

func (o *GetV1AudiencesMemberMemberIDDefaultOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AudiencesEntitiesAudienceEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
