// Code generated by go-swagger; DO NOT EDIT.

package ticketing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1TicketingTicketsParams creates a new GetV1TicketingTicketsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1TicketingTicketsParams() *GetV1TicketingTicketsParams {
	return &GetV1TicketingTicketsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1TicketingTicketsParamsWithTimeout creates a new GetV1TicketingTicketsParams object
// with the ability to set a timeout on a request.
func NewGetV1TicketingTicketsParamsWithTimeout(timeout time.Duration) *GetV1TicketingTicketsParams {
	return &GetV1TicketingTicketsParams{
		timeout: timeout,
	}
}

// NewGetV1TicketingTicketsParamsWithContext creates a new GetV1TicketingTicketsParams object
// with the ability to set a context for a request.
func NewGetV1TicketingTicketsParamsWithContext(ctx context.Context) *GetV1TicketingTicketsParams {
	return &GetV1TicketingTicketsParams{
		Context: ctx,
	}
}

// NewGetV1TicketingTicketsParamsWithHTTPClient creates a new GetV1TicketingTicketsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1TicketingTicketsParamsWithHTTPClient(client *http.Client) *GetV1TicketingTicketsParams {
	return &GetV1TicketingTicketsParams{
		HTTPClient: client,
	}
}

/*
GetV1TicketingTicketsParams contains all the parameters to send to the API endpoint

	for the get v1 ticketing tickets operation.

	Typically these are written to a http.Request.
*/
type GetV1TicketingTicketsParams struct {

	/* AssignedUser.

	   Filter tickets assigned to this user id
	*/
	AssignedUser *string

	// Page.
	//
	// Format: int32
	Page *int32

	// PerPage.
	//
	// Format: int32
	PerPage *int32

	/* State.

	   Filter tickets by state
	*/
	State *string

	/* TagMatchStrategy.

	   A matching strategy for the tags provided
	*/
	TagMatchStrategy *string

	/* Tags.

	   A comma separated list of tags
	*/
	Tags *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 ticketing tickets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1TicketingTicketsParams) WithDefaults() *GetV1TicketingTicketsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 ticketing tickets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1TicketingTicketsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithTimeout(timeout time.Duration) *GetV1TicketingTicketsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithContext(ctx context.Context) *GetV1TicketingTicketsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithHTTPClient(client *http.Client) *GetV1TicketingTicketsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssignedUser adds the assignedUser to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithAssignedUser(assignedUser *string) *GetV1TicketingTicketsParams {
	o.SetAssignedUser(assignedUser)
	return o
}

// SetAssignedUser adds the assignedUser to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetAssignedUser(assignedUser *string) {
	o.AssignedUser = assignedUser
}

// WithPage adds the page to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithPage(page *int32) *GetV1TicketingTicketsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetPage(page *int32) {
	o.Page = page
}

// WithPerPage adds the perPage to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithPerPage(perPage *int32) *GetV1TicketingTicketsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetPerPage(perPage *int32) {
	o.PerPage = perPage
}

// WithState adds the state to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithState(state *string) *GetV1TicketingTicketsParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetState(state *string) {
	o.State = state
}

// WithTagMatchStrategy adds the tagMatchStrategy to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithTagMatchStrategy(tagMatchStrategy *string) *GetV1TicketingTicketsParams {
	o.SetTagMatchStrategy(tagMatchStrategy)
	return o
}

// SetTagMatchStrategy adds the tagMatchStrategy to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetTagMatchStrategy(tagMatchStrategy *string) {
	o.TagMatchStrategy = tagMatchStrategy
}

// WithTags adds the tags to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) WithTags(tags *string) *GetV1TicketingTicketsParams {
	o.SetTags(tags)
	return o
}

// SetTags adds the tags to the get v1 ticketing tickets params
func (o *GetV1TicketingTicketsParams) SetTags(tags *string) {
	o.Tags = tags
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1TicketingTicketsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AssignedUser != nil {

		// query param assigned_user
		var qrAssignedUser string

		if o.AssignedUser != nil {
			qrAssignedUser = *o.AssignedUser
		}
		qAssignedUser := qrAssignedUser
		if qAssignedUser != "" {

			if err := r.SetQueryParam("assigned_user", qAssignedUser); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int32

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage int32

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt32(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	if o.State != nil {

		// query param state
		var qrState string

		if o.State != nil {
			qrState = *o.State
		}
		qState := qrState
		if qState != "" {

			if err := r.SetQueryParam("state", qState); err != nil {
				return err
			}
		}
	}

	if o.TagMatchStrategy != nil {

		// query param tag_match_strategy
		var qrTagMatchStrategy string

		if o.TagMatchStrategy != nil {
			qrTagMatchStrategy = *o.TagMatchStrategy
		}
		qTagMatchStrategy := qrTagMatchStrategy
		if qTagMatchStrategy != "" {

			if err := r.SetQueryParam("tag_match_strategy", qTagMatchStrategy); err != nil {
				return err
			}
		}
	}

	if o.Tags != nil {

		// query param tags
		var qrTags string

		if o.Tags != nil {
			qrTags = *o.Tags
		}
		qTags := qrTags
		if qTags != "" {

			if err := r.SetQueryParam("tags", qTags); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
