// Code generated by go-swagger; DO NOT EDIT.

package reporting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// NewUpdateSavedSearchParams creates a new UpdateSavedSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateSavedSearchParams() *UpdateSavedSearchParams {
	return &UpdateSavedSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSavedSearchParamsWithTimeout creates a new UpdateSavedSearchParams object
// with the ability to set a timeout on a request.
func NewUpdateSavedSearchParamsWithTimeout(timeout time.Duration) *UpdateSavedSearchParams {
	return &UpdateSavedSearchParams{
		timeout: timeout,
	}
}

// NewUpdateSavedSearchParamsWithContext creates a new UpdateSavedSearchParams object
// with the ability to set a context for a request.
func NewUpdateSavedSearchParamsWithContext(ctx context.Context) *UpdateSavedSearchParams {
	return &UpdateSavedSearchParams{
		Context: ctx,
	}
}

// NewUpdateSavedSearchParamsWithHTTPClient creates a new UpdateSavedSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateSavedSearchParamsWithHTTPClient(client *http.Client) *UpdateSavedSearchParams {
	return &UpdateSavedSearchParams{
		HTTPClient: client,
	}
}

/*
UpdateSavedSearchParams contains all the parameters to send to the API endpoint

	for the update saved search operation.

	Typically these are written to a http.Request.
*/
type UpdateSavedSearchParams struct {

	// ResourceType.
	ResourceType string

	// SavedSearchID.
	SavedSearchID string

	// UpdateSavedSearch.
	UpdateSavedSearch *models.UpdateSavedSearch

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update saved search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSavedSearchParams) WithDefaults() *UpdateSavedSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update saved search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSavedSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update saved search params
func (o *UpdateSavedSearchParams) WithTimeout(timeout time.Duration) *UpdateSavedSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update saved search params
func (o *UpdateSavedSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update saved search params
func (o *UpdateSavedSearchParams) WithContext(ctx context.Context) *UpdateSavedSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update saved search params
func (o *UpdateSavedSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update saved search params
func (o *UpdateSavedSearchParams) WithHTTPClient(client *http.Client) *UpdateSavedSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update saved search params
func (o *UpdateSavedSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceType adds the resourceType to the update saved search params
func (o *UpdateSavedSearchParams) WithResourceType(resourceType string) *UpdateSavedSearchParams {
	o.SetResourceType(resourceType)
	return o
}

// SetResourceType adds the resourceType to the update saved search params
func (o *UpdateSavedSearchParams) SetResourceType(resourceType string) {
	o.ResourceType = resourceType
}

// WithSavedSearchID adds the savedSearchID to the update saved search params
func (o *UpdateSavedSearchParams) WithSavedSearchID(savedSearchID string) *UpdateSavedSearchParams {
	o.SetSavedSearchID(savedSearchID)
	return o
}

// SetSavedSearchID adds the savedSearchId to the update saved search params
func (o *UpdateSavedSearchParams) SetSavedSearchID(savedSearchID string) {
	o.SavedSearchID = savedSearchID
}

// WithUpdateSavedSearch adds the updateSavedSearch to the update saved search params
func (o *UpdateSavedSearchParams) WithUpdateSavedSearch(updateSavedSearch *models.UpdateSavedSearch) *UpdateSavedSearchParams {
	o.SetUpdateSavedSearch(updateSavedSearch)
	return o
}

// SetUpdateSavedSearch adds the updateSavedSearch to the update saved search params
func (o *UpdateSavedSearchParams) SetUpdateSavedSearch(updateSavedSearch *models.UpdateSavedSearch) {
	o.UpdateSavedSearch = updateSavedSearch
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSavedSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resource_type
	if err := r.SetPathParam("resource_type", o.ResourceType); err != nil {
		return err
	}

	// path param saved_search_id
	if err := r.SetPathParam("saved_search_id", o.SavedSearchID); err != nil {
		return err
	}
	if o.UpdateSavedSearch != nil {
		if err := r.SetBodyParam(o.UpdateSavedSearch); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
