// Code generated by go-swagger; DO NOT EDIT.

package runbooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// CreateRunbookReader is a Reader for the CreateRunbook structure.
type CreateRunbookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRunbookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRunbookCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRunbookCreated creates a CreateRunbookCreated with default headers values
func NewCreateRunbookCreated() *CreateRunbookCreated {
	return &CreateRunbookCreated{}
}

/*
CreateRunbookCreated describes a response with status code 201, with default header values.

Create a new runbook for use with incidents.
*/
type CreateRunbookCreated struct {
	Payload *models.RunbookEntity
}

// IsSuccess returns true when this create runbook created response has a 2xx status code
func (o *CreateRunbookCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create runbook created response has a 3xx status code
func (o *CreateRunbookCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create runbook created response has a 4xx status code
func (o *CreateRunbookCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create runbook created response has a 5xx status code
func (o *CreateRunbookCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create runbook created response a status code equal to that given
func (o *CreateRunbookCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateRunbookCreated) Error() string {
	return fmt.Sprintf("[POST /v1/runbooks][%d] createRunbookCreated  %+v", 201, o.Payload)
}

func (o *CreateRunbookCreated) String() string {
	return fmt.Sprintf("[POST /v1/runbooks][%d] createRunbookCreated  %+v", 201, o.Payload)
}

func (o *CreateRunbookCreated) GetPayload() *models.RunbookEntity {
	return o.Payload
}

func (o *CreateRunbookCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RunbookEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
