// Code generated by go-swagger; DO NOT EDIT.

package runbooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteV1RunbooksExecutionsExecutionIDReader is a Reader for the DeleteV1RunbooksExecutionsExecutionID structure.
type DeleteV1RunbooksExecutionsExecutionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1RunbooksExecutionsExecutionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteV1RunbooksExecutionsExecutionIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteV1RunbooksExecutionsExecutionIDNoContent creates a DeleteV1RunbooksExecutionsExecutionIDNoContent with default headers values
func NewDeleteV1RunbooksExecutionsExecutionIDNoContent() *DeleteV1RunbooksExecutionsExecutionIDNoContent {
	return &DeleteV1RunbooksExecutionsExecutionIDNoContent{}
}

/*
DeleteV1RunbooksExecutionsExecutionIDNoContent describes a response with status code 204, with default header values.

Terminates a runbook execution, preventing any further steps from being executed
*/
type DeleteV1RunbooksExecutionsExecutionIDNoContent struct {
}

// IsSuccess returns true when this delete v1 runbooks executions execution Id no content response has a 2xx status code
func (o *DeleteV1RunbooksExecutionsExecutionIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 runbooks executions execution Id no content response has a 3xx status code
func (o *DeleteV1RunbooksExecutionsExecutionIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 runbooks executions execution Id no content response has a 4xx status code
func (o *DeleteV1RunbooksExecutionsExecutionIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 runbooks executions execution Id no content response has a 5xx status code
func (o *DeleteV1RunbooksExecutionsExecutionIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 runbooks executions execution Id no content response a status code equal to that given
func (o *DeleteV1RunbooksExecutionsExecutionIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteV1RunbooksExecutionsExecutionIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/runbooks/executions/{execution_id}][%d] deleteV1RunbooksExecutionsExecutionIdNoContent ", 204)
}

func (o *DeleteV1RunbooksExecutionsExecutionIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /v1/runbooks/executions/{execution_id}][%d] deleteV1RunbooksExecutionsExecutionIdNoContent ", 204)
}

func (o *DeleteV1RunbooksExecutionsExecutionIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
