// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteWebhookReader is a Reader for the DeleteWebhook structure.
type DeleteWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteWebhookNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteWebhookNoContent creates a DeleteWebhookNoContent with default headers values
func NewDeleteWebhookNoContent() *DeleteWebhookNoContent {
	return &DeleteWebhookNoContent{}
}

/*
DeleteWebhookNoContent describes a response with status code 204, with default header values.

Delete a specific webhook
*/
type DeleteWebhookNoContent struct {
}

// IsSuccess returns true when this delete webhook no content response has a 2xx status code
func (o *DeleteWebhookNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete webhook no content response has a 3xx status code
func (o *DeleteWebhookNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete webhook no content response has a 4xx status code
func (o *DeleteWebhookNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete webhook no content response has a 5xx status code
func (o *DeleteWebhookNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete webhook no content response a status code equal to that given
func (o *DeleteWebhookNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteWebhookNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/webhooks/{webhook_id}][%d] deleteWebhookNoContent ", 204)
}

func (o *DeleteWebhookNoContent) String() string {
	return fmt.Sprintf("[DELETE /v1/webhooks/{webhook_id}][%d] deleteWebhookNoContent ", 204)
}

func (o *DeleteWebhookNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
