// Code generated by go-swagger; DO NOT EDIT.

package webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ListWebhookDeliveriesReader is a Reader for the ListWebhookDeliveries structure.
type ListWebhookDeliveriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListWebhookDeliveriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListWebhookDeliveriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListWebhookDeliveriesOK creates a ListWebhookDeliveriesOK with default headers values
func NewListWebhookDeliveriesOK() *ListWebhookDeliveriesOK {
	return &ListWebhookDeliveriesOK{}
}

/*
ListWebhookDeliveriesOK describes a response with status code 200, with default header values.

Get webhook deliveries
*/
type ListWebhookDeliveriesOK struct {
}

// IsSuccess returns true when this list webhook deliveries o k response has a 2xx status code
func (o *ListWebhookDeliveriesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list webhook deliveries o k response has a 3xx status code
func (o *ListWebhookDeliveriesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list webhook deliveries o k response has a 4xx status code
func (o *ListWebhookDeliveriesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list webhook deliveries o k response has a 5xx status code
func (o *ListWebhookDeliveriesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list webhook deliveries o k response a status code equal to that given
func (o *ListWebhookDeliveriesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListWebhookDeliveriesOK) Error() string {
	return fmt.Sprintf("[GET /v1/webhooks/{webhook_id}/deliveries][%d] listWebhookDeliveriesOK ", 200)
}

func (o *ListWebhookDeliveriesOK) String() string {
	return fmt.Sprintf("[GET /v1/webhooks/{webhook_id}/deliveries][%d] listWebhookDeliveriesOK ", 200)
}

func (o *ListWebhookDeliveriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
