// Code generated by go-swagger; DO NOT EDIT.

package commenting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1CommentingCommentsCommentIDParams creates a new GetV1CommentingCommentsCommentIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1CommentingCommentsCommentIDParams() *GetV1CommentingCommentsCommentIDParams {
	return &GetV1CommentingCommentsCommentIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1CommentingCommentsCommentIDParamsWithTimeout creates a new GetV1CommentingCommentsCommentIDParams object
// with the ability to set a timeout on a request.
func NewGetV1CommentingCommentsCommentIDParamsWithTimeout(timeout time.Duration) *GetV1CommentingCommentsCommentIDParams {
	return &GetV1CommentingCommentsCommentIDParams{
		timeout: timeout,
	}
}

// NewGetV1CommentingCommentsCommentIDParamsWithContext creates a new GetV1CommentingCommentsCommentIDParams object
// with the ability to set a context for a request.
func NewGetV1CommentingCommentsCommentIDParamsWithContext(ctx context.Context) *GetV1CommentingCommentsCommentIDParams {
	return &GetV1CommentingCommentsCommentIDParams{
		Context: ctx,
	}
}

// NewGetV1CommentingCommentsCommentIDParamsWithHTTPClient creates a new GetV1CommentingCommentsCommentIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1CommentingCommentsCommentIDParamsWithHTTPClient(client *http.Client) *GetV1CommentingCommentsCommentIDParams {
	return &GetV1CommentingCommentsCommentIDParams{
		HTTPClient: client,
	}
}

/*
GetV1CommentingCommentsCommentIDParams contains all the parameters to send to the API endpoint

	for the get v1 commenting comments comment Id operation.

	Typically these are written to a http.Request.
*/
type GetV1CommentingCommentsCommentIDParams struct {

	// CommentID.
	CommentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 commenting comments comment Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1CommentingCommentsCommentIDParams) WithDefaults() *GetV1CommentingCommentsCommentIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 commenting comments comment Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1CommentingCommentsCommentIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 commenting comments comment Id params
func (o *GetV1CommentingCommentsCommentIDParams) WithTimeout(timeout time.Duration) *GetV1CommentingCommentsCommentIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 commenting comments comment Id params
func (o *GetV1CommentingCommentsCommentIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 commenting comments comment Id params
func (o *GetV1CommentingCommentsCommentIDParams) WithContext(ctx context.Context) *GetV1CommentingCommentsCommentIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 commenting comments comment Id params
func (o *GetV1CommentingCommentsCommentIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 commenting comments comment Id params
func (o *GetV1CommentingCommentsCommentIDParams) WithHTTPClient(client *http.Client) *GetV1CommentingCommentsCommentIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 commenting comments comment Id params
func (o *GetV1CommentingCommentsCommentIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCommentID adds the commentID to the get v1 commenting comments comment Id params
func (o *GetV1CommentingCommentsCommentIDParams) WithCommentID(commentID string) *GetV1CommentingCommentsCommentIDParams {
	o.SetCommentID(commentID)
	return o
}

// SetCommentID adds the commentId to the get v1 commenting comments comment Id params
func (o *GetV1CommentingCommentsCommentIDParams) SetCommentID(commentID string) {
	o.CommentID = commentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1CommentingCommentsCommentIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param comment_id
	if err := r.SetPathParam("comment_id", o.CommentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
