// Code generated by go-swagger; DO NOT EDIT.

package incident_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetV1LifecyclesMeasurementDefinitionsReader is a Reader for the GetV1LifecyclesMeasurementDefinitions structure.
type GetV1LifecyclesMeasurementDefinitionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1LifecyclesMeasurementDefinitionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1LifecyclesMeasurementDefinitionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetV1LifecyclesMeasurementDefinitionsOK creates a GetV1LifecyclesMeasurementDefinitionsOK with default headers values
func NewGetV1LifecyclesMeasurementDefinitionsOK() *GetV1LifecyclesMeasurementDefinitionsOK {
	return &GetV1LifecyclesMeasurementDefinitionsOK{}
}

/*
GetV1LifecyclesMeasurementDefinitionsOK describes a response with status code 200, with default header values.

List all of the measurement definitions in the organization
*/
type GetV1LifecyclesMeasurementDefinitionsOK struct {
}

// IsSuccess returns true when this get v1 lifecycles measurement definitions o k response has a 2xx status code
func (o *GetV1LifecyclesMeasurementDefinitionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 lifecycles measurement definitions o k response has a 3xx status code
func (o *GetV1LifecyclesMeasurementDefinitionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 lifecycles measurement definitions o k response has a 4xx status code
func (o *GetV1LifecyclesMeasurementDefinitionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 lifecycles measurement definitions o k response has a 5xx status code
func (o *GetV1LifecyclesMeasurementDefinitionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 lifecycles measurement definitions o k response a status code equal to that given
func (o *GetV1LifecyclesMeasurementDefinitionsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetV1LifecyclesMeasurementDefinitionsOK) Error() string {
	return fmt.Sprintf("[GET /v1/lifecycles/measurement_definitions][%d] getV1LifecyclesMeasurementDefinitionsOK ", 200)
}

func (o *GetV1LifecyclesMeasurementDefinitionsOK) String() string {
	return fmt.Sprintf("[GET /v1/lifecycles/measurement_definitions][%d] getV1LifecyclesMeasurementDefinitionsOK ", 200)
}

func (o *GetV1LifecyclesMeasurementDefinitionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
