// Code generated by go-swagger; DO NOT EDIT.

package catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// CreateServiceLinksReader is a Reader for the CreateServiceLinks structure.
type CreateServiceLinksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateServiceLinksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateServiceLinksCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateServiceLinksCreated creates a CreateServiceLinksCreated with default headers values
func NewCreateServiceLinksCreated() *CreateServiceLinksCreated {
	return &CreateServiceLinksCreated{}
}

/*
CreateServiceLinksCreated describes a response with status code 201, with default header values.

Creates a service with the appropriate integration for each external service ID passed
*/
type CreateServiceLinksCreated struct {
	Payload []*models.ServiceLinkEntity
}

// IsSuccess returns true when this create service links created response has a 2xx status code
func (o *CreateServiceLinksCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create service links created response has a 3xx status code
func (o *CreateServiceLinksCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create service links created response has a 4xx status code
func (o *CreateServiceLinksCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create service links created response has a 5xx status code
func (o *CreateServiceLinksCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create service links created response a status code equal to that given
func (o *CreateServiceLinksCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateServiceLinksCreated) Error() string {
	return fmt.Sprintf("[POST /v1/services/service_links][%d] createServiceLinksCreated  %+v", 201, o.Payload)
}

func (o *CreateServiceLinksCreated) String() string {
	return fmt.Sprintf("[POST /v1/services/service_links][%d] createServiceLinksCreated  %+v", 201, o.Payload)
}

func (o *CreateServiceLinksCreated) GetPayload() []*models.ServiceLinkEntity {
	return o.Payload
}

func (o *CreateServiceLinksCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
