// Code generated by go-swagger; DO NOT EDIT.

package catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// NewCreateServiceDependencyParams creates a new CreateServiceDependencyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateServiceDependencyParams() *CreateServiceDependencyParams {
	return &CreateServiceDependencyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateServiceDependencyParamsWithTimeout creates a new CreateServiceDependencyParams object
// with the ability to set a timeout on a request.
func NewCreateServiceDependencyParamsWithTimeout(timeout time.Duration) *CreateServiceDependencyParams {
	return &CreateServiceDependencyParams{
		timeout: timeout,
	}
}

// NewCreateServiceDependencyParamsWithContext creates a new CreateServiceDependencyParams object
// with the ability to set a context for a request.
func NewCreateServiceDependencyParamsWithContext(ctx context.Context) *CreateServiceDependencyParams {
	return &CreateServiceDependencyParams{
		Context: ctx,
	}
}

// NewCreateServiceDependencyParamsWithHTTPClient creates a new CreateServiceDependencyParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateServiceDependencyParamsWithHTTPClient(client *http.Client) *CreateServiceDependencyParams {
	return &CreateServiceDependencyParams{
		HTTPClient: client,
	}
}

/*
CreateServiceDependencyParams contains all the parameters to send to the API endpoint

	for the create service dependency operation.

	Typically these are written to a http.Request.
*/
type CreateServiceDependencyParams struct {

	// CreateServiceDependency.
	CreateServiceDependency *models.CreateServiceDependency

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create service dependency params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateServiceDependencyParams) WithDefaults() *CreateServiceDependencyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create service dependency params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateServiceDependencyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create service dependency params
func (o *CreateServiceDependencyParams) WithTimeout(timeout time.Duration) *CreateServiceDependencyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create service dependency params
func (o *CreateServiceDependencyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create service dependency params
func (o *CreateServiceDependencyParams) WithContext(ctx context.Context) *CreateServiceDependencyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create service dependency params
func (o *CreateServiceDependencyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create service dependency params
func (o *CreateServiceDependencyParams) WithHTTPClient(client *http.Client) *CreateServiceDependencyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create service dependency params
func (o *CreateServiceDependencyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateServiceDependency adds the createServiceDependency to the create service dependency params
func (o *CreateServiceDependencyParams) WithCreateServiceDependency(createServiceDependency *models.CreateServiceDependency) *CreateServiceDependencyParams {
	o.SetCreateServiceDependency(createServiceDependency)
	return o
}

// SetCreateServiceDependency adds the createServiceDependency to the create service dependency params
func (o *CreateServiceDependencyParams) SetCreateServiceDependency(createServiceDependency *models.CreateServiceDependency) {
	o.CreateServiceDependency = createServiceDependency
}

// WriteToRequest writes these params to a swagger request
func (o *CreateServiceDependencyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CreateServiceDependency != nil {
		if err := r.SetBodyParam(o.CreateServiceDependency); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
