// Code generated by go-swagger; DO NOT EDIT.

package catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// DeleteServiceDependencyReader is a Reader for the DeleteServiceDependency structure.
type DeleteServiceDependencyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServiceDependencyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteServiceDependencyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteServiceDependencyOK creates a DeleteServiceDependencyOK with default headers values
func NewDeleteServiceDependencyOK() *DeleteServiceDependencyOK {
	return &DeleteServiceDependencyOK{}
}

/*
DeleteServiceDependencyOK describes a response with status code 200, with default header values.

Deletes a single service dependency
*/
type DeleteServiceDependencyOK struct {
	Payload *models.ServiceDependencyEntity
}

// IsSuccess returns true when this delete service dependency o k response has a 2xx status code
func (o *DeleteServiceDependencyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete service dependency o k response has a 3xx status code
func (o *DeleteServiceDependencyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete service dependency o k response has a 4xx status code
func (o *DeleteServiceDependencyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete service dependency o k response has a 5xx status code
func (o *DeleteServiceDependencyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete service dependency o k response a status code equal to that given
func (o *DeleteServiceDependencyOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteServiceDependencyOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/service_dependencies/{service_dependency_id}][%d] deleteServiceDependencyOK  %+v", 200, o.Payload)
}

func (o *DeleteServiceDependencyOK) String() string {
	return fmt.Sprintf("[DELETE /v1/service_dependencies/{service_dependency_id}][%d] deleteServiceDependencyOK  %+v", 200, o.Payload)
}

func (o *DeleteServiceDependencyOK) GetPayload() *models.ServiceDependencyEntity {
	return o.Payload
}

func (o *DeleteServiceDependencyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceDependencyEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
