// Code generated by go-swagger; DO NOT EDIT.

package catalog_entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// DeleteFunctionalityReader is a Reader for the DeleteFunctionality structure.
type DeleteFunctionalityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFunctionalityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteFunctionalityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteFunctionalityOK creates a DeleteFunctionalityOK with default headers values
func NewDeleteFunctionalityOK() *DeleteFunctionalityOK {
	return &DeleteFunctionalityOK{}
}

/*
DeleteFunctionalityOK describes a response with status code 200, with default header values.

Archive a functionality
*/
type DeleteFunctionalityOK struct {
	Payload *models.FunctionalityEntity
}

// IsSuccess returns true when this delete functionality o k response has a 2xx status code
func (o *DeleteFunctionalityOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete functionality o k response has a 3xx status code
func (o *DeleteFunctionalityOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete functionality o k response has a 4xx status code
func (o *DeleteFunctionalityOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete functionality o k response has a 5xx status code
func (o *DeleteFunctionalityOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete functionality o k response a status code equal to that given
func (o *DeleteFunctionalityOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteFunctionalityOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/functionalities/{functionality_id}][%d] deleteFunctionalityOK  %+v", 200, o.Payload)
}

func (o *DeleteFunctionalityOK) String() string {
	return fmt.Sprintf("[DELETE /v1/functionalities/{functionality_id}][%d] deleteFunctionalityOK  %+v", 200, o.Payload)
}

func (o *DeleteFunctionalityOK) GetPayload() *models.FunctionalityEntity {
	return o.Payload
}

func (o *DeleteFunctionalityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FunctionalityEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
