// Code generated by go-swagger; DO NOT EDIT.

package signals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteTeamEscalationPolicyReader is a Reader for the DeleteTeamEscalationPolicy structure.
type DeleteTeamEscalationPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTeamEscalationPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteTeamEscalationPolicyNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteTeamEscalationPolicyNoContent creates a DeleteTeamEscalationPolicyNoContent with default headers values
func NewDeleteTeamEscalationPolicyNoContent() *DeleteTeamEscalationPolicyNoContent {
	return &DeleteTeamEscalationPolicyNoContent{}
}

/*
DeleteTeamEscalationPolicyNoContent describes a response with status code 204, with default header values.

Delete a Signals escalation policy by ID
*/
type DeleteTeamEscalationPolicyNoContent struct {
}

// IsSuccess returns true when this delete team escalation policy no content response has a 2xx status code
func (o *DeleteTeamEscalationPolicyNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete team escalation policy no content response has a 3xx status code
func (o *DeleteTeamEscalationPolicyNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete team escalation policy no content response has a 4xx status code
func (o *DeleteTeamEscalationPolicyNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete team escalation policy no content response has a 5xx status code
func (o *DeleteTeamEscalationPolicyNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete team escalation policy no content response a status code equal to that given
func (o *DeleteTeamEscalationPolicyNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteTeamEscalationPolicyNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/teams/{team_id}/escalation_policies/{id}][%d] deleteTeamEscalationPolicyNoContent ", 204)
}

func (o *DeleteTeamEscalationPolicyNoContent) String() string {
	return fmt.Sprintf("[DELETE /v1/teams/{team_id}/escalation_policies/{id}][%d] deleteTeamEscalationPolicyNoContent ", 204)
}

func (o *DeleteTeamEscalationPolicyNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
