// Code generated by go-swagger; DO NOT EDIT.

package signals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetV1SignalsEventSourcesReader is a Reader for the GetV1SignalsEventSources structure.
type GetV1SignalsEventSourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1SignalsEventSourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1SignalsEventSourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetV1SignalsEventSourcesOK creates a GetV1SignalsEventSourcesOK with default headers values
func NewGetV1SignalsEventSourcesOK() *GetV1SignalsEventSourcesOK {
	return &GetV1SignalsEventSourcesOK{}
}

/*
GetV1SignalsEventSourcesOK describes a response with status code 200, with default header values.

List all Signals event sources for the authenticated user.
*/
type GetV1SignalsEventSourcesOK struct {
}

// IsSuccess returns true when this get v1 signals event sources o k response has a 2xx status code
func (o *GetV1SignalsEventSourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 signals event sources o k response has a 3xx status code
func (o *GetV1SignalsEventSourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 signals event sources o k response has a 4xx status code
func (o *GetV1SignalsEventSourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 signals event sources o k response has a 5xx status code
func (o *GetV1SignalsEventSourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 signals event sources o k response a status code equal to that given
func (o *GetV1SignalsEventSourcesOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetV1SignalsEventSourcesOK) Error() string {
	return fmt.Sprintf("[GET /v1/signals/event_sources][%d] getV1SignalsEventSourcesOK ", 200)
}

func (o *GetV1SignalsEventSourcesOK) String() string {
	return fmt.Sprintf("[GET /v1/signals/event_sources][%d] getV1SignalsEventSourcesOK ", 200)
}

func (o *GetV1SignalsEventSourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
