// Code generated by go-swagger; DO NOT EDIT.

package signals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetV1SignalsTransposersReader is a Reader for the GetV1SignalsTransposers structure.
type GetV1SignalsTransposersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1SignalsTransposersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1SignalsTransposersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetV1SignalsTransposersOK creates a GetV1SignalsTransposersOK with default headers values
func NewGetV1SignalsTransposersOK() *GetV1SignalsTransposersOK {
	return &GetV1SignalsTransposersOK{}
}

/*
GetV1SignalsTransposersOK describes a response with status code 200, with default header values.

get Transposer(s)
*/
type GetV1SignalsTransposersOK struct {
}

// IsSuccess returns true when this get v1 signals transposers o k response has a 2xx status code
func (o *GetV1SignalsTransposersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 signals transposers o k response has a 3xx status code
func (o *GetV1SignalsTransposersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 signals transposers o k response has a 4xx status code
func (o *GetV1SignalsTransposersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 signals transposers o k response has a 5xx status code
func (o *GetV1SignalsTransposersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 signals transposers o k response a status code equal to that given
func (o *GetV1SignalsTransposersOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetV1SignalsTransposersOK) Error() string {
	return fmt.Sprintf("[GET /v1/signals/transposers][%d] getV1SignalsTransposersOK ", 200)
}

func (o *GetV1SignalsTransposersOK) String() string {
	return fmt.Sprintf("[GET /v1/signals/transposers][%d] getV1SignalsTransposersOK ", 200)
}

func (o *GetV1SignalsTransposersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
