// Code generated by go-swagger; DO NOT EDIT.

package signals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetV1SignalsEmailTargetsIDReader is a Reader for the GetV1SignalsEmailTargetsID structure.
type GetV1SignalsEmailTargetsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1SignalsEmailTargetsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1SignalsEmailTargetsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetV1SignalsEmailTargetsIDOK creates a GetV1SignalsEmailTargetsIDOK with default headers values
func NewGetV1SignalsEmailTargetsIDOK() *GetV1SignalsEmailTargetsIDOK {
	return &GetV1SignalsEmailTargetsIDOK{}
}

/*
GetV1SignalsEmailTargetsIDOK describes a response with status code 200, with default header values.

Get a Signals email target by ID
*/
type GetV1SignalsEmailTargetsIDOK struct {
}

// IsSuccess returns true when this get v1 signals email targets Id o k response has a 2xx status code
func (o *GetV1SignalsEmailTargetsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 signals email targets Id o k response has a 3xx status code
func (o *GetV1SignalsEmailTargetsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 signals email targets Id o k response has a 4xx status code
func (o *GetV1SignalsEmailTargetsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 signals email targets Id o k response has a 5xx status code
func (o *GetV1SignalsEmailTargetsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 signals email targets Id o k response a status code equal to that given
func (o *GetV1SignalsEmailTargetsIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetV1SignalsEmailTargetsIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/signals/email_targets/{id}][%d] getV1SignalsEmailTargetsIdOK ", 200)
}

func (o *GetV1SignalsEmailTargetsIDOK) String() string {
	return fmt.Sprintf("[GET /v1/signals/email_targets/{id}][%d] getV1SignalsEmailTargetsIdOK ", 200)
}

func (o *GetV1SignalsEmailTargetsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
