// Code generated by go-swagger; DO NOT EDIT.

package signals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ListTeamOnCallSchedulesReader is a Reader for the ListTeamOnCallSchedules structure.
type ListTeamOnCallSchedulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListTeamOnCallSchedulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListTeamOnCallSchedulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListTeamOnCallSchedulesOK creates a ListTeamOnCallSchedulesOK with default headers values
func NewListTeamOnCallSchedulesOK() *ListTeamOnCallSchedulesOK {
	return &ListTeamOnCallSchedulesOK{}
}

/*
ListTeamOnCallSchedulesOK describes a response with status code 200, with default header values.

List all Signals on-call schedules for a team.
*/
type ListTeamOnCallSchedulesOK struct {
}

// IsSuccess returns true when this list team on call schedules o k response has a 2xx status code
func (o *ListTeamOnCallSchedulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list team on call schedules o k response has a 3xx status code
func (o *ListTeamOnCallSchedulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list team on call schedules o k response has a 4xx status code
func (o *ListTeamOnCallSchedulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list team on call schedules o k response has a 5xx status code
func (o *ListTeamOnCallSchedulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list team on call schedules o k response a status code equal to that given
func (o *ListTeamOnCallSchedulesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListTeamOnCallSchedulesOK) Error() string {
	return fmt.Sprintf("[GET /v1/teams/{team_id}/on_call_schedules][%d] listTeamOnCallSchedulesOK ", 200)
}

func (o *ListTeamOnCallSchedulesOK) String() string {
	return fmt.Sprintf("[GET /v1/teams/{team_id}/on_call_schedules][%d] listTeamOnCallSchedulesOK ", 200)
}

func (o *ListTeamOnCallSchedulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
