// Code generated by go-swagger; DO NOT EDIT.

package retrospectives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// CreateIncidentRetrospectiveFieldReader is a Reader for the CreateIncidentRetrospectiveField structure.
type CreateIncidentRetrospectiveFieldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateIncidentRetrospectiveFieldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateIncidentRetrospectiveFieldOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateIncidentRetrospectiveFieldOK creates a CreateIncidentRetrospectiveFieldOK with default headers values
func NewCreateIncidentRetrospectiveFieldOK() *CreateIncidentRetrospectiveFieldOK {
	return &CreateIncidentRetrospectiveFieldOK{}
}

/*
CreateIncidentRetrospectiveFieldOK describes a response with status code 200, with default header values.

Add a new field to an incident retrospective
*/
type CreateIncidentRetrospectiveFieldOK struct {
	Payload *models.IncidentsRetrospectiveFieldEntity
}

// IsSuccess returns true when this create incident retrospective field o k response has a 2xx status code
func (o *CreateIncidentRetrospectiveFieldOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create incident retrospective field o k response has a 3xx status code
func (o *CreateIncidentRetrospectiveFieldOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create incident retrospective field o k response has a 4xx status code
func (o *CreateIncidentRetrospectiveFieldOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create incident retrospective field o k response has a 5xx status code
func (o *CreateIncidentRetrospectiveFieldOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create incident retrospective field o k response a status code equal to that given
func (o *CreateIncidentRetrospectiveFieldOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateIncidentRetrospectiveFieldOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/incidents/{incident_id}/retrospectives/{retrospective_id}/fields][%d] createIncidentRetrospectiveFieldOK  %+v", 200, o.Payload)
}

func (o *CreateIncidentRetrospectiveFieldOK) String() string {
	return fmt.Sprintf("[PATCH /v1/incidents/{incident_id}/retrospectives/{retrospective_id}/fields][%d] createIncidentRetrospectiveFieldOK  %+v", 200, o.Payload)
}

func (o *CreateIncidentRetrospectiveFieldOK) GetPayload() *models.IncidentsRetrospectiveFieldEntity {
	return o.Payload
}

func (o *CreateIncidentRetrospectiveFieldOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IncidentsRetrospectiveFieldEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
