// Code generated by go-swagger; DO NOT EDIT.

package retrospectives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// ListPostMortemReportsReader is a Reader for the ListPostMortemReports structure.
type ListPostMortemReportsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPostMortemReportsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPostMortemReportsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListPostMortemReportsOK creates a ListPostMortemReportsOK with default headers values
func NewListPostMortemReportsOK() *ListPostMortemReportsOK {
	return &ListPostMortemReportsOK{}
}

/*
ListPostMortemReportsOK describes a response with status code 200, with default header values.

List all reports
*/
type ListPostMortemReportsOK struct {
	Payload *models.PostMortemsPostMortemReportEntityPaginated
}

// IsSuccess returns true when this list post mortem reports o k response has a 2xx status code
func (o *ListPostMortemReportsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list post mortem reports o k response has a 3xx status code
func (o *ListPostMortemReportsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list post mortem reports o k response has a 4xx status code
func (o *ListPostMortemReportsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list post mortem reports o k response has a 5xx status code
func (o *ListPostMortemReportsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list post mortem reports o k response a status code equal to that given
func (o *ListPostMortemReportsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListPostMortemReportsOK) Error() string {
	return fmt.Sprintf("[GET /v1/post_mortems/reports][%d] listPostMortemReportsOK  %+v", 200, o.Payload)
}

func (o *ListPostMortemReportsOK) String() string {
	return fmt.Sprintf("[GET /v1/post_mortems/reports][%d] listPostMortemReportsOK  %+v", 200, o.Payload)
}

func (o *ListPostMortemReportsOK) GetPayload() *models.PostMortemsPostMortemReportEntityPaginated {
	return o.Payload
}

func (o *ListPostMortemReportsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostMortemsPostMortemReportEntityPaginated)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
