// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSlackEmojiActionParams creates a new GetSlackEmojiActionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSlackEmojiActionParams() *GetSlackEmojiActionParams {
	return &GetSlackEmojiActionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSlackEmojiActionParamsWithTimeout creates a new GetSlackEmojiActionParams object
// with the ability to set a timeout on a request.
func NewGetSlackEmojiActionParamsWithTimeout(timeout time.Duration) *GetSlackEmojiActionParams {
	return &GetSlackEmojiActionParams{
		timeout: timeout,
	}
}

// NewGetSlackEmojiActionParamsWithContext creates a new GetSlackEmojiActionParams object
// with the ability to set a context for a request.
func NewGetSlackEmojiActionParamsWithContext(ctx context.Context) *GetSlackEmojiActionParams {
	return &GetSlackEmojiActionParams{
		Context: ctx,
	}
}

// NewGetSlackEmojiActionParamsWithHTTPClient creates a new GetSlackEmojiActionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSlackEmojiActionParamsWithHTTPClient(client *http.Client) *GetSlackEmojiActionParams {
	return &GetSlackEmojiActionParams{
		HTTPClient: client,
	}
}

/*
GetSlackEmojiActionParams contains all the parameters to send to the API endpoint

	for the get slack emoji action operation.

	Typically these are written to a http.Request.
*/
type GetSlackEmojiActionParams struct {

	/* ConnectionID.

	   Slack Connection UUID
	*/
	ConnectionID string

	// EmojiActionID.
	EmojiActionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get slack emoji action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSlackEmojiActionParams) WithDefaults() *GetSlackEmojiActionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get slack emoji action params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSlackEmojiActionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get slack emoji action params
func (o *GetSlackEmojiActionParams) WithTimeout(timeout time.Duration) *GetSlackEmojiActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get slack emoji action params
func (o *GetSlackEmojiActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get slack emoji action params
func (o *GetSlackEmojiActionParams) WithContext(ctx context.Context) *GetSlackEmojiActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get slack emoji action params
func (o *GetSlackEmojiActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get slack emoji action params
func (o *GetSlackEmojiActionParams) WithHTTPClient(client *http.Client) *GetSlackEmojiActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get slack emoji action params
func (o *GetSlackEmojiActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionID adds the connectionID to the get slack emoji action params
func (o *GetSlackEmojiActionParams) WithConnectionID(connectionID string) *GetSlackEmojiActionParams {
	o.SetConnectionID(connectionID)
	return o
}

// SetConnectionID adds the connectionId to the get slack emoji action params
func (o *GetSlackEmojiActionParams) SetConnectionID(connectionID string) {
	o.ConnectionID = connectionID
}

// WithEmojiActionID adds the emojiActionID to the get slack emoji action params
func (o *GetSlackEmojiActionParams) WithEmojiActionID(emojiActionID string) *GetSlackEmojiActionParams {
	o.SetEmojiActionID(emojiActionID)
	return o
}

// SetEmojiActionID adds the emojiActionId to the get slack emoji action params
func (o *GetSlackEmojiActionParams) SetEmojiActionID(emojiActionID string) {
	o.EmojiActionID = emojiActionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSlackEmojiActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param connection_id
	if err := r.SetPathParam("connection_id", o.ConnectionID); err != nil {
		return err
	}

	// path param emoji_action_id
	if err := r.SetPathParam("emoji_action_id", o.EmojiActionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
