// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetV1IntegrationsMicrosoftTeamsV2OnCallReader is a Reader for the GetV1IntegrationsMicrosoftTeamsV2OnCall structure.
type GetV1IntegrationsMicrosoftTeamsV2OnCallReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1IntegrationsMicrosoftTeamsV2OnCallOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetV1IntegrationsMicrosoftTeamsV2OnCallOK creates a GetV1IntegrationsMicrosoftTeamsV2OnCallOK with default headers values
func NewGetV1IntegrationsMicrosoftTeamsV2OnCallOK() *GetV1IntegrationsMicrosoftTeamsV2OnCallOK {
	return &GetV1IntegrationsMicrosoftTeamsV2OnCallOK{}
}

/*
GetV1IntegrationsMicrosoftTeamsV2OnCallOK describes a response with status code 200, with default header values.

get OnCall(s)
*/
type GetV1IntegrationsMicrosoftTeamsV2OnCallOK struct {
}

// IsSuccess returns true when this get v1 integrations microsoft teams v2 on call o k response has a 2xx status code
func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 integrations microsoft teams v2 on call o k response has a 3xx status code
func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 integrations microsoft teams v2 on call o k response has a 4xx status code
func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 integrations microsoft teams v2 on call o k response has a 5xx status code
func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 integrations microsoft teams v2 on call o k response a status code equal to that given
func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallOK) Error() string {
	return fmt.Sprintf("[GET /v1/integrations/microsoft_teams_v2/on_call][%d] getV1IntegrationsMicrosoftTeamsV2OnCallOK ", 200)
}

func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallOK) String() string {
	return fmt.Sprintf("[GET /v1/integrations/microsoft_teams_v2/on_call][%d] getV1IntegrationsMicrosoftTeamsV2OnCallOK ", 200)
}

func (o *GetV1IntegrationsMicrosoftTeamsV2OnCallOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
