// Code generated by go-swagger; DO NOT EDIT.

package integrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// PatchV1IntegrationsConnectionsSlugConnectionIDReader is a Reader for the PatchV1IntegrationsConnectionsSlugConnectionID structure.
type PatchV1IntegrationsConnectionsSlugConnectionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchV1IntegrationsConnectionsSlugConnectionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchV1IntegrationsConnectionsSlugConnectionIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPatchV1IntegrationsConnectionsSlugConnectionIDOK creates a PatchV1IntegrationsConnectionsSlugConnectionIDOK with default headers values
func NewPatchV1IntegrationsConnectionsSlugConnectionIDOK() *PatchV1IntegrationsConnectionsSlugConnectionIDOK {
	return &PatchV1IntegrationsConnectionsSlugConnectionIDOK{}
}

/*
PatchV1IntegrationsConnectionsSlugConnectionIDOK describes a response with status code 200, with default header values.

Update the integration connection with the provided data
*/
type PatchV1IntegrationsConnectionsSlugConnectionIDOK struct {
	Payload *models.IntegrationsConnectionEntity
}

// IsSuccess returns true when this patch v1 integrations connections slug connection Id o k response has a 2xx status code
func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch v1 integrations connections slug connection Id o k response has a 3xx status code
func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch v1 integrations connections slug connection Id o k response has a 4xx status code
func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch v1 integrations connections slug connection Id o k response has a 5xx status code
func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch v1 integrations connections slug connection Id o k response a status code equal to that given
func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/integrations/connections/{slug}/{connection_id}][%d] patchV1IntegrationsConnectionsSlugConnectionIdOK  %+v", 200, o.Payload)
}

func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) String() string {
	return fmt.Sprintf("[PATCH /v1/integrations/connections/{slug}/{connection_id}][%d] patchV1IntegrationsConnectionsSlugConnectionIdOK  %+v", 200, o.Payload)
}

func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) GetPayload() *models.IntegrationsConnectionEntity {
	return o.Payload
}

func (o *PatchV1IntegrationsConnectionsSlugConnectionIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IntegrationsConnectionEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
