// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// NewCreateChecklistTemplateParams creates a new CreateChecklistTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateChecklistTemplateParams() *CreateChecklistTemplateParams {
	return &CreateChecklistTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateChecklistTemplateParamsWithTimeout creates a new CreateChecklistTemplateParams object
// with the ability to set a timeout on a request.
func NewCreateChecklistTemplateParamsWithTimeout(timeout time.Duration) *CreateChecklistTemplateParams {
	return &CreateChecklistTemplateParams{
		timeout: timeout,
	}
}

// NewCreateChecklistTemplateParamsWithContext creates a new CreateChecklistTemplateParams object
// with the ability to set a context for a request.
func NewCreateChecklistTemplateParamsWithContext(ctx context.Context) *CreateChecklistTemplateParams {
	return &CreateChecklistTemplateParams{
		Context: ctx,
	}
}

// NewCreateChecklistTemplateParamsWithHTTPClient creates a new CreateChecklistTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateChecklistTemplateParamsWithHTTPClient(client *http.Client) *CreateChecklistTemplateParams {
	return &CreateChecklistTemplateParams{
		HTTPClient: client,
	}
}

/*
CreateChecklistTemplateParams contains all the parameters to send to the API endpoint

	for the create checklist template operation.

	Typically these are written to a http.Request.
*/
type CreateChecklistTemplateParams struct {

	// CreateChecklistTemplate.
	CreateChecklistTemplate *models.CreateChecklistTemplate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create checklist template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateChecklistTemplateParams) WithDefaults() *CreateChecklistTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create checklist template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateChecklistTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create checklist template params
func (o *CreateChecklistTemplateParams) WithTimeout(timeout time.Duration) *CreateChecklistTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create checklist template params
func (o *CreateChecklistTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create checklist template params
func (o *CreateChecklistTemplateParams) WithContext(ctx context.Context) *CreateChecklistTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create checklist template params
func (o *CreateChecklistTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create checklist template params
func (o *CreateChecklistTemplateParams) WithHTTPClient(client *http.Client) *CreateChecklistTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create checklist template params
func (o *CreateChecklistTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateChecklistTemplate adds the createChecklistTemplate to the create checklist template params
func (o *CreateChecklistTemplateParams) WithCreateChecklistTemplate(createChecklistTemplate *models.CreateChecklistTemplate) *CreateChecklistTemplateParams {
	o.SetCreateChecklistTemplate(createChecklistTemplate)
	return o
}

// SetCreateChecklistTemplate adds the createChecklistTemplate to the create checklist template params
func (o *CreateChecklistTemplateParams) SetCreateChecklistTemplate(createChecklistTemplate *models.CreateChecklistTemplate) {
	o.CreateChecklistTemplate = createChecklistTemplate
}

// WriteToRequest writes these params to a swagger request
func (o *CreateChecklistTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CreateChecklistTemplate != nil {
		if err := r.SetBodyParam(o.CreateChecklistTemplate); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
