// Code generated by go-swagger; DO NOT EDIT.

package functionalities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// GetV1FunctionalitiesReader is a Reader for the GetV1Functionalities structure.
type GetV1FunctionalitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1FunctionalitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1FunctionalitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetV1FunctionalitiesOK creates a GetV1FunctionalitiesOK with default headers values
func NewGetV1FunctionalitiesOK() *GetV1FunctionalitiesOK {
	return &GetV1FunctionalitiesOK{}
}

/* GetV1FunctionalitiesOK describes a response with status code 200, with default header values.

List all of the functionalities that have been added to the organiation
*/
type GetV1FunctionalitiesOK struct {
	Payload *models.FunctionalityEntity
}

func (o *GetV1FunctionalitiesOK) Error() string {
	return fmt.Sprintf("[GET /v1/functionalities][%d] getV1FunctionalitiesOK  %+v", 200, o.Payload)
}
func (o *GetV1FunctionalitiesOK) GetPayload() *models.FunctionalityEntity {
	return o.Payload
}

func (o *GetV1FunctionalitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FunctionalityEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
