// Code generated by go-swagger; DO NOT EDIT.

package functionalities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1FunctionalitiesFunctionalityIDServicesParams creates a new GetV1FunctionalitiesFunctionalityIDServicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1FunctionalitiesFunctionalityIDServicesParams() *GetV1FunctionalitiesFunctionalityIDServicesParams {
	return &GetV1FunctionalitiesFunctionalityIDServicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1FunctionalitiesFunctionalityIDServicesParamsWithTimeout creates a new GetV1FunctionalitiesFunctionalityIDServicesParams object
// with the ability to set a timeout on a request.
func NewGetV1FunctionalitiesFunctionalityIDServicesParamsWithTimeout(timeout time.Duration) *GetV1FunctionalitiesFunctionalityIDServicesParams {
	return &GetV1FunctionalitiesFunctionalityIDServicesParams{
		timeout: timeout,
	}
}

// NewGetV1FunctionalitiesFunctionalityIDServicesParamsWithContext creates a new GetV1FunctionalitiesFunctionalityIDServicesParams object
// with the ability to set a context for a request.
func NewGetV1FunctionalitiesFunctionalityIDServicesParamsWithContext(ctx context.Context) *GetV1FunctionalitiesFunctionalityIDServicesParams {
	return &GetV1FunctionalitiesFunctionalityIDServicesParams{
		Context: ctx,
	}
}

// NewGetV1FunctionalitiesFunctionalityIDServicesParamsWithHTTPClient creates a new GetV1FunctionalitiesFunctionalityIDServicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1FunctionalitiesFunctionalityIDServicesParamsWithHTTPClient(client *http.Client) *GetV1FunctionalitiesFunctionalityIDServicesParams {
	return &GetV1FunctionalitiesFunctionalityIDServicesParams{
		HTTPClient: client,
	}
}

/*
GetV1FunctionalitiesFunctionalityIDServicesParams contains all the parameters to send to the API endpoint

	for the get v1 functionalities functionality Id services operation.

	Typically these are written to a http.Request.
*/
type GetV1FunctionalitiesFunctionalityIDServicesParams struct {

	// FunctionalityID.
	//
	// Format: int32
	FunctionalityID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 functionalities functionality Id services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) WithDefaults() *GetV1FunctionalitiesFunctionalityIDServicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 functionalities functionality Id services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 functionalities functionality Id services params
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) WithTimeout(timeout time.Duration) *GetV1FunctionalitiesFunctionalityIDServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 functionalities functionality Id services params
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 functionalities functionality Id services params
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) WithContext(ctx context.Context) *GetV1FunctionalitiesFunctionalityIDServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 functionalities functionality Id services params
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 functionalities functionality Id services params
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) WithHTTPClient(client *http.Client) *GetV1FunctionalitiesFunctionalityIDServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 functionalities functionality Id services params
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFunctionalityID adds the functionalityID to the get v1 functionalities functionality Id services params
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) WithFunctionalityID(functionalityID int32) *GetV1FunctionalitiesFunctionalityIDServicesParams {
	o.SetFunctionalityID(functionalityID)
	return o
}

// SetFunctionalityID adds the functionalityId to the get v1 functionalities functionality Id services params
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) SetFunctionalityID(functionalityID int32) {
	o.FunctionalityID = functionalityID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1FunctionalitiesFunctionalityIDServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param functionality_id
	if err := r.SetPathParam("functionality_id", swag.FormatInt32(o.FunctionalityID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
