// Code generated by go-swagger; DO NOT EDIT.

package severities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// GetV1SeveritiesSeveritySlugReader is a Reader for the GetV1SeveritiesSeveritySlug structure.
type GetV1SeveritiesSeveritySlugReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1SeveritiesSeveritySlugReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1SeveritiesSeveritySlugOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetV1SeveritiesSeveritySlugOK creates a GetV1SeveritiesSeveritySlugOK with default headers values
func NewGetV1SeveritiesSeveritySlugOK() *GetV1SeveritiesSeveritySlugOK {
	return &GetV1SeveritiesSeveritySlugOK{}
}

/*
GetV1SeveritiesSeveritySlugOK describes a response with status code 200, with default header values.

Retrieve a specific severity
*/
type GetV1SeveritiesSeveritySlugOK struct {
	Payload *models.SeverityEntity
}

// IsSuccess returns true when this get v1 severities severity slug o k response has a 2xx status code
func (o *GetV1SeveritiesSeveritySlugOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 severities severity slug o k response has a 3xx status code
func (o *GetV1SeveritiesSeveritySlugOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 severities severity slug o k response has a 4xx status code
func (o *GetV1SeveritiesSeveritySlugOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 severities severity slug o k response has a 5xx status code
func (o *GetV1SeveritiesSeveritySlugOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 severities severity slug o k response a status code equal to that given
func (o *GetV1SeveritiesSeveritySlugOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetV1SeveritiesSeveritySlugOK) Error() string {
	return fmt.Sprintf("[GET /v1/severities/{severity_slug}][%d] getV1SeveritiesSeveritySlugOK  %+v", 200, o.Payload)
}

func (o *GetV1SeveritiesSeveritySlugOK) String() string {
	return fmt.Sprintf("[GET /v1/severities/{severity_slug}][%d] getV1SeveritiesSeveritySlugOK  %+v", 200, o.Payload)
}

func (o *GetV1SeveritiesSeveritySlugOK) GetPayload() *models.SeverityEntity {
	return o.Payload
}

func (o *GetV1SeveritiesSeveritySlugOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SeverityEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
