// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// NewCreateIncidentImpactParams creates a new CreateIncidentImpactParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateIncidentImpactParams() *CreateIncidentImpactParams {
	return &CreateIncidentImpactParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateIncidentImpactParamsWithTimeout creates a new CreateIncidentImpactParams object
// with the ability to set a timeout on a request.
func NewCreateIncidentImpactParamsWithTimeout(timeout time.Duration) *CreateIncidentImpactParams {
	return &CreateIncidentImpactParams{
		timeout: timeout,
	}
}

// NewCreateIncidentImpactParamsWithContext creates a new CreateIncidentImpactParams object
// with the ability to set a context for a request.
func NewCreateIncidentImpactParamsWithContext(ctx context.Context) *CreateIncidentImpactParams {
	return &CreateIncidentImpactParams{
		Context: ctx,
	}
}

// NewCreateIncidentImpactParamsWithHTTPClient creates a new CreateIncidentImpactParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateIncidentImpactParamsWithHTTPClient(client *http.Client) *CreateIncidentImpactParams {
	return &CreateIncidentImpactParams{
		HTTPClient: client,
	}
}

/*
CreateIncidentImpactParams contains all the parameters to send to the API endpoint

	for the create incident impact operation.

	Typically these are written to a http.Request.
*/
type CreateIncidentImpactParams struct {

	// CreateIncidentImpact.
	CreateIncidentImpact *models.CreateIncidentImpact

	// IncidentID.
	IncidentID string

	// Type.
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create incident impact params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateIncidentImpactParams) WithDefaults() *CreateIncidentImpactParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create incident impact params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateIncidentImpactParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create incident impact params
func (o *CreateIncidentImpactParams) WithTimeout(timeout time.Duration) *CreateIncidentImpactParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create incident impact params
func (o *CreateIncidentImpactParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create incident impact params
func (o *CreateIncidentImpactParams) WithContext(ctx context.Context) *CreateIncidentImpactParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create incident impact params
func (o *CreateIncidentImpactParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create incident impact params
func (o *CreateIncidentImpactParams) WithHTTPClient(client *http.Client) *CreateIncidentImpactParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create incident impact params
func (o *CreateIncidentImpactParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateIncidentImpact adds the createIncidentImpact to the create incident impact params
func (o *CreateIncidentImpactParams) WithCreateIncidentImpact(createIncidentImpact *models.CreateIncidentImpact) *CreateIncidentImpactParams {
	o.SetCreateIncidentImpact(createIncidentImpact)
	return o
}

// SetCreateIncidentImpact adds the createIncidentImpact to the create incident impact params
func (o *CreateIncidentImpactParams) SetCreateIncidentImpact(createIncidentImpact *models.CreateIncidentImpact) {
	o.CreateIncidentImpact = createIncidentImpact
}

// WithIncidentID adds the incidentID to the create incident impact params
func (o *CreateIncidentImpactParams) WithIncidentID(incidentID string) *CreateIncidentImpactParams {
	o.SetIncidentID(incidentID)
	return o
}

// SetIncidentID adds the incidentId to the create incident impact params
func (o *CreateIncidentImpactParams) SetIncidentID(incidentID string) {
	o.IncidentID = incidentID
}

// WithType adds the typeVar to the create incident impact params
func (o *CreateIncidentImpactParams) WithType(typeVar string) *CreateIncidentImpactParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the create incident impact params
func (o *CreateIncidentImpactParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *CreateIncidentImpactParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CreateIncidentImpact != nil {
		if err := r.SetBodyParam(o.CreateIncidentImpact); err != nil {
			return err
		}
	}

	// path param incident_id
	if err := r.SetPathParam("incident_id", o.IncidentID); err != nil {
		return err
	}

	// path param type
	if err := r.SetPathParam("type", o.Type); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
