// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// CreateIncidentReader is a Reader for the CreateIncident structure.
type CreateIncidentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateIncidentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateIncidentCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateIncidentCreated creates a CreateIncidentCreated with default headers values
func NewCreateIncidentCreated() *CreateIncidentCreated {
	return &CreateIncidentCreated{}
}

/*
CreateIncidentCreated describes a response with status code 201, with default header values.

Create a new incident
*/
type CreateIncidentCreated struct {
	Payload *models.IncidentEntity
}

// IsSuccess returns true when this create incident created response has a 2xx status code
func (o *CreateIncidentCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create incident created response has a 3xx status code
func (o *CreateIncidentCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create incident created response has a 4xx status code
func (o *CreateIncidentCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create incident created response has a 5xx status code
func (o *CreateIncidentCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create incident created response a status code equal to that given
func (o *CreateIncidentCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateIncidentCreated) Error() string {
	return fmt.Sprintf("[POST /v1/incidents][%d] createIncidentCreated  %+v", 201, o.Payload)
}

func (o *CreateIncidentCreated) String() string {
	return fmt.Sprintf("[POST /v1/incidents][%d] createIncidentCreated  %+v", 201, o.Payload)
}

func (o *CreateIncidentCreated) GetPayload() *models.IncidentEntity {
	return o.Payload
}

func (o *CreateIncidentCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IncidentEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
