// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// NewCreateIncidentParams creates a new CreateIncidentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateIncidentParams() *CreateIncidentParams {
	return &CreateIncidentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateIncidentParamsWithTimeout creates a new CreateIncidentParams object
// with the ability to set a timeout on a request.
func NewCreateIncidentParamsWithTimeout(timeout time.Duration) *CreateIncidentParams {
	return &CreateIncidentParams{
		timeout: timeout,
	}
}

// NewCreateIncidentParamsWithContext creates a new CreateIncidentParams object
// with the ability to set a context for a request.
func NewCreateIncidentParamsWithContext(ctx context.Context) *CreateIncidentParams {
	return &CreateIncidentParams{
		Context: ctx,
	}
}

// NewCreateIncidentParamsWithHTTPClient creates a new CreateIncidentParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateIncidentParamsWithHTTPClient(client *http.Client) *CreateIncidentParams {
	return &CreateIncidentParams{
		HTTPClient: client,
	}
}

/*
CreateIncidentParams contains all the parameters to send to the API endpoint

	for the create incident operation.

	Typically these are written to a http.Request.
*/
type CreateIncidentParams struct {

	// CreateIncident.
	CreateIncident *models.CreateIncident

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create incident params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateIncidentParams) WithDefaults() *CreateIncidentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create incident params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateIncidentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create incident params
func (o *CreateIncidentParams) WithTimeout(timeout time.Duration) *CreateIncidentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create incident params
func (o *CreateIncidentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create incident params
func (o *CreateIncidentParams) WithContext(ctx context.Context) *CreateIncidentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create incident params
func (o *CreateIncidentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create incident params
func (o *CreateIncidentParams) WithHTTPClient(client *http.Client) *CreateIncidentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create incident params
func (o *CreateIncidentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateIncident adds the createIncident to the create incident params
func (o *CreateIncidentParams) WithCreateIncident(createIncident *models.CreateIncident) *CreateIncidentParams {
	o.SetCreateIncident(createIncident)
	return o
}

// SetCreateIncident adds the createIncident to the create incident params
func (o *CreateIncidentParams) SetCreateIncident(createIncident *models.CreateIncident) {
	o.CreateIncident = createIncident
}

// WriteToRequest writes these params to a swagger request
func (o *CreateIncidentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CreateIncident != nil {
		if err := r.SetBodyParam(o.CreateIncident); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
