// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteIncidentTeamAssignmentReader is a Reader for the DeleteIncidentTeamAssignment structure.
type DeleteIncidentTeamAssignmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteIncidentTeamAssignmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteIncidentTeamAssignmentNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteIncidentTeamAssignmentNoContent creates a DeleteIncidentTeamAssignmentNoContent with default headers values
func NewDeleteIncidentTeamAssignmentNoContent() *DeleteIncidentTeamAssignmentNoContent {
	return &DeleteIncidentTeamAssignmentNoContent{}
}

/*
DeleteIncidentTeamAssignmentNoContent describes a response with status code 204, with default header values.

Unassign a team from an incident
*/
type DeleteIncidentTeamAssignmentNoContent struct {
}

// IsSuccess returns true when this delete incident team assignment no content response has a 2xx status code
func (o *DeleteIncidentTeamAssignmentNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete incident team assignment no content response has a 3xx status code
func (o *DeleteIncidentTeamAssignmentNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete incident team assignment no content response has a 4xx status code
func (o *DeleteIncidentTeamAssignmentNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete incident team assignment no content response has a 5xx status code
func (o *DeleteIncidentTeamAssignmentNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete incident team assignment no content response a status code equal to that given
func (o *DeleteIncidentTeamAssignmentNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteIncidentTeamAssignmentNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/incidents/{incident_id}/team_assignments/{team_assignment_id}][%d] deleteIncidentTeamAssignmentNoContent ", 204)
}

func (o *DeleteIncidentTeamAssignmentNoContent) String() string {
	return fmt.Sprintf("[DELETE /v1/incidents/{incident_id}/team_assignments/{team_assignment_id}][%d] deleteIncidentTeamAssignmentNoContent ", 204)
}

func (o *DeleteIncidentTeamAssignmentNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
