// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteIncidentLinkParams creates a new DeleteIncidentLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteIncidentLinkParams() *DeleteIncidentLinkParams {
	return &DeleteIncidentLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteIncidentLinkParamsWithTimeout creates a new DeleteIncidentLinkParams object
// with the ability to set a timeout on a request.
func NewDeleteIncidentLinkParamsWithTimeout(timeout time.Duration) *DeleteIncidentLinkParams {
	return &DeleteIncidentLinkParams{
		timeout: timeout,
	}
}

// NewDeleteIncidentLinkParamsWithContext creates a new DeleteIncidentLinkParams object
// with the ability to set a context for a request.
func NewDeleteIncidentLinkParamsWithContext(ctx context.Context) *DeleteIncidentLinkParams {
	return &DeleteIncidentLinkParams{
		Context: ctx,
	}
}

// NewDeleteIncidentLinkParamsWithHTTPClient creates a new DeleteIncidentLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteIncidentLinkParamsWithHTTPClient(client *http.Client) *DeleteIncidentLinkParams {
	return &DeleteIncidentLinkParams{
		HTTPClient: client,
	}
}

/*
DeleteIncidentLinkParams contains all the parameters to send to the API endpoint

	for the delete incident link operation.

	Typically these are written to a http.Request.
*/
type DeleteIncidentLinkParams struct {

	// IncidentID.
	IncidentID string

	// LinkID.
	LinkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete incident link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteIncidentLinkParams) WithDefaults() *DeleteIncidentLinkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete incident link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteIncidentLinkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete incident link params
func (o *DeleteIncidentLinkParams) WithTimeout(timeout time.Duration) *DeleteIncidentLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete incident link params
func (o *DeleteIncidentLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete incident link params
func (o *DeleteIncidentLinkParams) WithContext(ctx context.Context) *DeleteIncidentLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete incident link params
func (o *DeleteIncidentLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete incident link params
func (o *DeleteIncidentLinkParams) WithHTTPClient(client *http.Client) *DeleteIncidentLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete incident link params
func (o *DeleteIncidentLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIncidentID adds the incidentID to the delete incident link params
func (o *DeleteIncidentLinkParams) WithIncidentID(incidentID string) *DeleteIncidentLinkParams {
	o.SetIncidentID(incidentID)
	return o
}

// SetIncidentID adds the incidentId to the delete incident link params
func (o *DeleteIncidentLinkParams) SetIncidentID(incidentID string) {
	o.IncidentID = incidentID
}

// WithLinkID adds the linkID to the delete incident link params
func (o *DeleteIncidentLinkParams) WithLinkID(linkID string) *DeleteIncidentLinkParams {
	o.SetLinkID(linkID)
	return o
}

// SetLinkID adds the linkId to the delete incident link params
func (o *DeleteIncidentLinkParams) SetLinkID(linkID string) {
	o.LinkID = linkID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteIncidentLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param incident_id
	if err := r.SetPathParam("incident_id", o.IncidentID); err != nil {
		return err
	}

	// path param link_id
	if err := r.SetPathParam("link_id", o.LinkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
