// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// GetConferenceBridgeTranslationReader is a Reader for the GetConferenceBridgeTranslation structure.
type GetConferenceBridgeTranslationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConferenceBridgeTranslationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConferenceBridgeTranslationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetConferenceBridgeTranslationOK creates a GetConferenceBridgeTranslationOK with default headers values
func NewGetConferenceBridgeTranslationOK() *GetConferenceBridgeTranslationOK {
	return &GetConferenceBridgeTranslationOK{}
}

/*
GetConferenceBridgeTranslationOK describes a response with status code 200, with default header values.

Retrieve the translations for a specific conference bridge
*/
type GetConferenceBridgeTranslationOK struct {
	Payload *models.IncidentsConferenceBridgeEntity
}

// IsSuccess returns true when this get conference bridge translation o k response has a 2xx status code
func (o *GetConferenceBridgeTranslationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get conference bridge translation o k response has a 3xx status code
func (o *GetConferenceBridgeTranslationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get conference bridge translation o k response has a 4xx status code
func (o *GetConferenceBridgeTranslationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get conference bridge translation o k response has a 5xx status code
func (o *GetConferenceBridgeTranslationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get conference bridge translation o k response a status code equal to that given
func (o *GetConferenceBridgeTranslationOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetConferenceBridgeTranslationOK) Error() string {
	return fmt.Sprintf("[GET /v1/incidents/{incident_id}/conference_bridges/{id}/translations/{language_code}][%d] getConferenceBridgeTranslationOK  %+v", 200, o.Payload)
}

func (o *GetConferenceBridgeTranslationOK) String() string {
	return fmt.Sprintf("[GET /v1/incidents/{incident_id}/conference_bridges/{id}/translations/{language_code}][%d] getConferenceBridgeTranslationOK  %+v", 200, o.Payload)
}

func (o *GetConferenceBridgeTranslationOK) GetPayload() *models.IncidentsConferenceBridgeEntity {
	return o.Payload
}

func (o *GetConferenceBridgeTranslationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IncidentsConferenceBridgeEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
