// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAiIncidentSummaryVoteStatusReader is a Reader for the GetAiIncidentSummaryVoteStatus structure.
type GetAiIncidentSummaryVoteStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAiIncidentSummaryVoteStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAiIncidentSummaryVoteStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAiIncidentSummaryVoteStatusOK creates a GetAiIncidentSummaryVoteStatusOK with default headers values
func NewGetAiIncidentSummaryVoteStatusOK() *GetAiIncidentSummaryVoteStatusOK {
	return &GetAiIncidentSummaryVoteStatusOK{}
}

/*
GetAiIncidentSummaryVoteStatusOK describes a response with status code 200, with default header values.

Get the current user's vote status for an AI-generated incident summary
*/
type GetAiIncidentSummaryVoteStatusOK struct {
}

// IsSuccess returns true when this get ai incident summary vote status o k response has a 2xx status code
func (o *GetAiIncidentSummaryVoteStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get ai incident summary vote status o k response has a 3xx status code
func (o *GetAiIncidentSummaryVoteStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ai incident summary vote status o k response has a 4xx status code
func (o *GetAiIncidentSummaryVoteStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ai incident summary vote status o k response has a 5xx status code
func (o *GetAiIncidentSummaryVoteStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get ai incident summary vote status o k response a status code equal to that given
func (o *GetAiIncidentSummaryVoteStatusOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAiIncidentSummaryVoteStatusOK) Error() string {
	return fmt.Sprintf("[GET /v1/ai/summarize_incident/{incident_id}/{generated_summary_id}/voted][%d] getAiIncidentSummaryVoteStatusOK ", 200)
}

func (o *GetAiIncidentSummaryVoteStatusOK) String() string {
	return fmt.Sprintf("[GET /v1/ai/summarize_incident/{incident_id}/{generated_summary_id}/voted][%d] getAiIncidentSummaryVoteStatusOK ", 200)
}

func (o *GetAiIncidentSummaryVoteStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
