// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/firehydrant/api-client-go/models"
)

// NewPatchV1IncidentsIncidentIDActionItemsActionItemIDParams creates a new PatchV1IncidentsIncidentIDActionItemsActionItemIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchV1IncidentsIncidentIDActionItemsActionItemIDParams() *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	return &PatchV1IncidentsIncidentIDActionItemsActionItemIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchV1IncidentsIncidentIDActionItemsActionItemIDParamsWithTimeout creates a new PatchV1IncidentsIncidentIDActionItemsActionItemIDParams object
// with the ability to set a timeout on a request.
func NewPatchV1IncidentsIncidentIDActionItemsActionItemIDParamsWithTimeout(timeout time.Duration) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	return &PatchV1IncidentsIncidentIDActionItemsActionItemIDParams{
		timeout: timeout,
	}
}

// NewPatchV1IncidentsIncidentIDActionItemsActionItemIDParamsWithContext creates a new PatchV1IncidentsIncidentIDActionItemsActionItemIDParams object
// with the ability to set a context for a request.
func NewPatchV1IncidentsIncidentIDActionItemsActionItemIDParamsWithContext(ctx context.Context) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	return &PatchV1IncidentsIncidentIDActionItemsActionItemIDParams{
		Context: ctx,
	}
}

// NewPatchV1IncidentsIncidentIDActionItemsActionItemIDParamsWithHTTPClient creates a new PatchV1IncidentsIncidentIDActionItemsActionItemIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchV1IncidentsIncidentIDActionItemsActionItemIDParamsWithHTTPClient(client *http.Client) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	return &PatchV1IncidentsIncidentIDActionItemsActionItemIDParams{
		HTTPClient: client,
	}
}

/* PatchV1IncidentsIncidentIDActionItemsActionItemIDParams contains all the parameters to send to the API endpoint
   for the patch v1 incidents incident Id action items action item Id operation.

   Typically these are written to a http.Request.
*/
type PatchV1IncidentsIncidentIDActionItemsActionItemIDParams struct {

	// V1IncidentsIncidentIDActionItems.
	V1IncidentsIncidentIDActionItems *models.PatchV1IncidentsIncidentIDActionItems

	// ActionItemID.
	ActionItemID string

	// IncidentID.
	//
	// Format: int32
	IncidentID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch v1 incidents incident Id action items action item Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) WithDefaults() *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch v1 incidents incident Id action items action item Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) WithTimeout(timeout time.Duration) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) WithContext(ctx context.Context) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) WithHTTPClient(client *http.Client) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithV1IncidentsIncidentIDActionItems adds the v1IncidentsIncidentIDActionItems to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) WithV1IncidentsIncidentIDActionItems(v1IncidentsIncidentIDActionItems *models.PatchV1IncidentsIncidentIDActionItems) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	o.SetV1IncidentsIncidentIDActionItems(v1IncidentsIncidentIDActionItems)
	return o
}

// SetV1IncidentsIncidentIDActionItems adds the v1IncidentsIncidentIdActionItems to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) SetV1IncidentsIncidentIDActionItems(v1IncidentsIncidentIDActionItems *models.PatchV1IncidentsIncidentIDActionItems) {
	o.V1IncidentsIncidentIDActionItems = v1IncidentsIncidentIDActionItems
}

// WithActionItemID adds the actionItemID to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) WithActionItemID(actionItemID string) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	o.SetActionItemID(actionItemID)
	return o
}

// SetActionItemID adds the actionItemId to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) SetActionItemID(actionItemID string) {
	o.ActionItemID = actionItemID
}

// WithIncidentID adds the incidentID to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) WithIncidentID(incidentID int32) *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams {
	o.SetIncidentID(incidentID)
	return o
}

// SetIncidentID adds the incidentId to the patch v1 incidents incident Id action items action item Id params
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) SetIncidentID(incidentID int32) {
	o.IncidentID = incidentID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchV1IncidentsIncidentIDActionItemsActionItemIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.V1IncidentsIncidentIDActionItems != nil {
		if err := r.SetBodyParam(o.V1IncidentsIncidentIDActionItems); err != nil {
			return err
		}
	}

	// path param action_item_id
	if err := r.SetPathParam("action_item_id", o.ActionItemID); err != nil {
		return err
	}

	// path param incident_id
	if err := r.SetPathParam("incident_id", swag.FormatInt32(o.IncidentID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
