// Code generated by go-swagger; DO NOT EDIT.

package incidents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// NewPatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams creates a new PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams() *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	return &PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParamsWithTimeout creates a new PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams object
// with the ability to set a timeout on a request.
func NewPatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParamsWithTimeout(timeout time.Duration) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	return &PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams{
		timeout: timeout,
	}
}

// NewPatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParamsWithContext creates a new PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams object
// with the ability to set a context for a request.
func NewPatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParamsWithContext(ctx context.Context) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	return &PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams{
		Context: ctx,
	}
}

// NewPatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParamsWithHTTPClient creates a new PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParamsWithHTTPClient(client *http.Client) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	return &PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams{
		HTTPClient: client,
	}
}

/*
PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams contains all the parameters to send to the API endpoint

	for the patch v1 incidents incident Id generic chat messages message Id operation.

	Typically these are written to a http.Request.
*/
type PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams struct {

	// V1IncidentsIncidentIDGenericChatMessages.
	V1IncidentsIncidentIDGenericChatMessages *models.PatchV1IncidentsIncidentIDGenericChatMessages

	// IncidentID.
	IncidentID string

	// MessageID.
	MessageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch v1 incidents incident Id generic chat messages message Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) WithDefaults() *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch v1 incidents incident Id generic chat messages message Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) WithTimeout(timeout time.Duration) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) WithContext(ctx context.Context) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) WithHTTPClient(client *http.Client) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithV1IncidentsIncidentIDGenericChatMessages adds the v1IncidentsIncidentIDGenericChatMessages to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) WithV1IncidentsIncidentIDGenericChatMessages(v1IncidentsIncidentIDGenericChatMessages *models.PatchV1IncidentsIncidentIDGenericChatMessages) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	o.SetV1IncidentsIncidentIDGenericChatMessages(v1IncidentsIncidentIDGenericChatMessages)
	return o
}

// SetV1IncidentsIncidentIDGenericChatMessages adds the v1IncidentsIncidentIdGenericChatMessages to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) SetV1IncidentsIncidentIDGenericChatMessages(v1IncidentsIncidentIDGenericChatMessages *models.PatchV1IncidentsIncidentIDGenericChatMessages) {
	o.V1IncidentsIncidentIDGenericChatMessages = v1IncidentsIncidentIDGenericChatMessages
}

// WithIncidentID adds the incidentID to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) WithIncidentID(incidentID string) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	o.SetIncidentID(incidentID)
	return o
}

// SetIncidentID adds the incidentId to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) SetIncidentID(incidentID string) {
	o.IncidentID = incidentID
}

// WithMessageID adds the messageID to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) WithMessageID(messageID string) *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams {
	o.SetMessageID(messageID)
	return o
}

// SetMessageID adds the messageId to the patch v1 incidents incident Id generic chat messages message Id params
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) SetMessageID(messageID string) {
	o.MessageID = messageID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchV1IncidentsIncidentIDGenericChatMessagesMessageIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.V1IncidentsIncidentIDGenericChatMessages != nil {
		if err := r.SetBodyParam(o.V1IncidentsIncidentIDGenericChatMessages); err != nil {
			return err
		}
	}

	// path param incident_id
	if err := r.SetPathParam("incident_id", o.IncidentID); err != nil {
		return err
	}

	// path param message_id
	if err := r.SetPathParam("message_id", o.MessageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
