// Code generated by go-swagger; DO NOT EDIT.

package custom_fields

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// PostV1CustomFieldsDefinitionsReader is a Reader for the PostV1CustomFieldsDefinitions structure.
type PostV1CustomFieldsDefinitionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1CustomFieldsDefinitionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostV1CustomFieldsDefinitionsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostV1CustomFieldsDefinitionsCreated creates a PostV1CustomFieldsDefinitionsCreated with default headers values
func NewPostV1CustomFieldsDefinitionsCreated() *PostV1CustomFieldsDefinitionsCreated {
	return &PostV1CustomFieldsDefinitionsCreated{}
}

/*
PostV1CustomFieldsDefinitionsCreated describes a response with status code 201, with default header values.

Create a new custom field definition
*/
type PostV1CustomFieldsDefinitionsCreated struct {
	Payload *models.OrganizationsCustomFieldDefinitionEntity
}

// IsSuccess returns true when this post v1 custom fields definitions created response has a 2xx status code
func (o *PostV1CustomFieldsDefinitionsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 custom fields definitions created response has a 3xx status code
func (o *PostV1CustomFieldsDefinitionsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 custom fields definitions created response has a 4xx status code
func (o *PostV1CustomFieldsDefinitionsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 custom fields definitions created response has a 5xx status code
func (o *PostV1CustomFieldsDefinitionsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 custom fields definitions created response a status code equal to that given
func (o *PostV1CustomFieldsDefinitionsCreated) IsCode(code int) bool {
	return code == 201
}

func (o *PostV1CustomFieldsDefinitionsCreated) Error() string {
	return fmt.Sprintf("[POST /v1/custom_fields/definitions][%d] postV1CustomFieldsDefinitionsCreated  %+v", 201, o.Payload)
}

func (o *PostV1CustomFieldsDefinitionsCreated) String() string {
	return fmt.Sprintf("[POST /v1/custom_fields/definitions][%d] postV1CustomFieldsDefinitionsCreated  %+v", 201, o.Payload)
}

func (o *PostV1CustomFieldsDefinitionsCreated) GetPayload() *models.OrganizationsCustomFieldDefinitionEntity {
	return o.Payload
}

func (o *PostV1CustomFieldsDefinitionsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrganizationsCustomFieldDefinitionEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
