// Code generated by go-swagger; DO NOT EDIT.

package account_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListEntitlementsParams creates a new ListEntitlementsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListEntitlementsParams() *ListEntitlementsParams {
	return &ListEntitlementsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListEntitlementsParamsWithTimeout creates a new ListEntitlementsParams object
// with the ability to set a timeout on a request.
func NewListEntitlementsParamsWithTimeout(timeout time.Duration) *ListEntitlementsParams {
	return &ListEntitlementsParams{
		timeout: timeout,
	}
}

// NewListEntitlementsParamsWithContext creates a new ListEntitlementsParams object
// with the ability to set a context for a request.
func NewListEntitlementsParamsWithContext(ctx context.Context) *ListEntitlementsParams {
	return &ListEntitlementsParams{
		Context: ctx,
	}
}

// NewListEntitlementsParamsWithHTTPClient creates a new ListEntitlementsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListEntitlementsParamsWithHTTPClient(client *http.Client) *ListEntitlementsParams {
	return &ListEntitlementsParams{
		HTTPClient: client,
	}
}

/*
ListEntitlementsParams contains all the parameters to send to the API endpoint

	for the list entitlements operation.

	Typically these are written to a http.Request.
*/
type ListEntitlementsParams struct {

	/* Name.

	   Name of Entitlement
	*/
	Name *string

	/* Type.

	   Type of Entitlement
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list entitlements params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEntitlementsParams) WithDefaults() *ListEntitlementsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list entitlements params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEntitlementsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list entitlements params
func (o *ListEntitlementsParams) WithTimeout(timeout time.Duration) *ListEntitlementsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list entitlements params
func (o *ListEntitlementsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list entitlements params
func (o *ListEntitlementsParams) WithContext(ctx context.Context) *ListEntitlementsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list entitlements params
func (o *ListEntitlementsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list entitlements params
func (o *ListEntitlementsParams) WithHTTPClient(client *http.Client) *ListEntitlementsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list entitlements params
func (o *ListEntitlementsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the list entitlements params
func (o *ListEntitlementsParams) WithName(name *string) *ListEntitlementsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list entitlements params
func (o *ListEntitlementsParams) SetName(name *string) {
	o.Name = name
}

// WithType adds the typeVar to the list entitlements params
func (o *ListEntitlementsParams) WithType(typeVar *string) *ListEntitlementsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the list entitlements params
func (o *ListEntitlementsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *ListEntitlementsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
