// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteV1TeamsTeamIDEscalationPoliciesIDParams creates a new DeleteV1TeamsTeamIDEscalationPoliciesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteV1TeamsTeamIDEscalationPoliciesIDParams() *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	return &DeleteV1TeamsTeamIDEscalationPoliciesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteV1TeamsTeamIDEscalationPoliciesIDParamsWithTimeout creates a new DeleteV1TeamsTeamIDEscalationPoliciesIDParams object
// with the ability to set a timeout on a request.
func NewDeleteV1TeamsTeamIDEscalationPoliciesIDParamsWithTimeout(timeout time.Duration) *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	return &DeleteV1TeamsTeamIDEscalationPoliciesIDParams{
		timeout: timeout,
	}
}

// NewDeleteV1TeamsTeamIDEscalationPoliciesIDParamsWithContext creates a new DeleteV1TeamsTeamIDEscalationPoliciesIDParams object
// with the ability to set a context for a request.
func NewDeleteV1TeamsTeamIDEscalationPoliciesIDParamsWithContext(ctx context.Context) *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	return &DeleteV1TeamsTeamIDEscalationPoliciesIDParams{
		Context: ctx,
	}
}

// NewDeleteV1TeamsTeamIDEscalationPoliciesIDParamsWithHTTPClient creates a new DeleteV1TeamsTeamIDEscalationPoliciesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteV1TeamsTeamIDEscalationPoliciesIDParamsWithHTTPClient(client *http.Client) *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	return &DeleteV1TeamsTeamIDEscalationPoliciesIDParams{
		HTTPClient: client,
	}
}

/*
DeleteV1TeamsTeamIDEscalationPoliciesIDParams contains all the parameters to send to the API endpoint

	for the delete v1 teams team Id escalation policies Id operation.

	Typically these are written to a http.Request.
*/
type DeleteV1TeamsTeamIDEscalationPoliciesIDParams struct {

	// ID.
	//
	// Format: int32
	ID int32

	/* TeamID.

	   The ID of the team for which you want to manage Signals escalation policies.
	*/
	TeamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete v1 teams team Id escalation policies Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) WithDefaults() *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete v1 teams team Id escalation policies Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) WithTimeout(timeout time.Duration) *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) WithContext(ctx context.Context) *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) WithHTTPClient(client *http.Client) *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) WithID(id int32) *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) SetID(id int32) {
	o.ID = id
}

// WithTeamID adds the teamID to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) WithTeamID(teamID string) *DeleteV1TeamsTeamIDEscalationPoliciesIDParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the delete v1 teams team Id escalation policies Id params
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) SetTeamID(teamID string) {
	o.TeamID = teamID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteV1TeamsTeamIDEscalationPoliciesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	// path param team_id
	if err := r.SetPathParam("team_id", o.TeamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
