// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1TeamsTeamIDSignalRulesIDParams creates a new GetV1TeamsTeamIDSignalRulesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1TeamsTeamIDSignalRulesIDParams() *GetV1TeamsTeamIDSignalRulesIDParams {
	return &GetV1TeamsTeamIDSignalRulesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1TeamsTeamIDSignalRulesIDParamsWithTimeout creates a new GetV1TeamsTeamIDSignalRulesIDParams object
// with the ability to set a timeout on a request.
func NewGetV1TeamsTeamIDSignalRulesIDParamsWithTimeout(timeout time.Duration) *GetV1TeamsTeamIDSignalRulesIDParams {
	return &GetV1TeamsTeamIDSignalRulesIDParams{
		timeout: timeout,
	}
}

// NewGetV1TeamsTeamIDSignalRulesIDParamsWithContext creates a new GetV1TeamsTeamIDSignalRulesIDParams object
// with the ability to set a context for a request.
func NewGetV1TeamsTeamIDSignalRulesIDParamsWithContext(ctx context.Context) *GetV1TeamsTeamIDSignalRulesIDParams {
	return &GetV1TeamsTeamIDSignalRulesIDParams{
		Context: ctx,
	}
}

// NewGetV1TeamsTeamIDSignalRulesIDParamsWithHTTPClient creates a new GetV1TeamsTeamIDSignalRulesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1TeamsTeamIDSignalRulesIDParamsWithHTTPClient(client *http.Client) *GetV1TeamsTeamIDSignalRulesIDParams {
	return &GetV1TeamsTeamIDSignalRulesIDParams{
		HTTPClient: client,
	}
}

/*
GetV1TeamsTeamIDSignalRulesIDParams contains all the parameters to send to the API endpoint

	for the get v1 teams team Id signal rules Id operation.

	Typically these are written to a http.Request.
*/
type GetV1TeamsTeamIDSignalRulesIDParams struct {

	// ID.
	ID string

	// TeamID.
	TeamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 teams team Id signal rules Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1TeamsTeamIDSignalRulesIDParams) WithDefaults() *GetV1TeamsTeamIDSignalRulesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 teams team Id signal rules Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1TeamsTeamIDSignalRulesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) WithTimeout(timeout time.Duration) *GetV1TeamsTeamIDSignalRulesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) WithContext(ctx context.Context) *GetV1TeamsTeamIDSignalRulesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) WithHTTPClient(client *http.Client) *GetV1TeamsTeamIDSignalRulesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) WithID(id string) *GetV1TeamsTeamIDSignalRulesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) SetID(id string) {
	o.ID = id
}

// WithTeamID adds the teamID to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) WithTeamID(teamID string) *GetV1TeamsTeamIDSignalRulesIDParams {
	o.SetTeamID(teamID)
	return o
}

// SetTeamID adds the teamId to the get v1 teams team Id signal rules Id params
func (o *GetV1TeamsTeamIDSignalRulesIDParams) SetTeamID(teamID string) {
	o.TeamID = teamID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1TeamsTeamIDSignalRulesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param team_id
	if err := r.SetPathParam("team_id", o.TeamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
