// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostV1TeamsTeamIDSignalRulesReader is a Reader for the PostV1TeamsTeamIDSignalRules structure.
type PostV1TeamsTeamIDSignalRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1TeamsTeamIDSignalRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostV1TeamsTeamIDSignalRulesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/teams/{team_id}/signal_rules] postV1TeamsTeamIdSignalRules", response, response.Code())
	}
}

// NewPostV1TeamsTeamIDSignalRulesCreated creates a PostV1TeamsTeamIDSignalRulesCreated with default headers values
func NewPostV1TeamsTeamIDSignalRulesCreated() *PostV1TeamsTeamIDSignalRulesCreated {
	return &PostV1TeamsTeamIDSignalRulesCreated{}
}

/*
PostV1TeamsTeamIDSignalRulesCreated describes a response with status code 201, with default header values.

Create a Signals rule for a team.
*/
type PostV1TeamsTeamIDSignalRulesCreated struct {
}

// IsSuccess returns true when this post v1 teams team Id signal rules created response has a 2xx status code
func (o *PostV1TeamsTeamIDSignalRulesCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 teams team Id signal rules created response has a 3xx status code
func (o *PostV1TeamsTeamIDSignalRulesCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 teams team Id signal rules created response has a 4xx status code
func (o *PostV1TeamsTeamIDSignalRulesCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 teams team Id signal rules created response has a 5xx status code
func (o *PostV1TeamsTeamIDSignalRulesCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 teams team Id signal rules created response a status code equal to that given
func (o *PostV1TeamsTeamIDSignalRulesCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post v1 teams team Id signal rules created response
func (o *PostV1TeamsTeamIDSignalRulesCreated) Code() int {
	return 201
}

func (o *PostV1TeamsTeamIDSignalRulesCreated) Error() string {
	return fmt.Sprintf("[POST /v1/teams/{team_id}/signal_rules][%d] postV1TeamsTeamIdSignalRulesCreated ", 201)
}

func (o *PostV1TeamsTeamIDSignalRulesCreated) String() string {
	return fmt.Sprintf("[POST /v1/teams/{team_id}/signal_rules][%d] postV1TeamsTeamIdSignalRulesCreated ", 201)
}

func (o *PostV1TeamsTeamIDSignalRulesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
