// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// DeleteV1ServicesServiceIDReader is a Reader for the DeleteV1ServicesServiceID structure.
type DeleteV1ServicesServiceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteV1ServicesServiceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteV1ServicesServiceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteV1ServicesServiceIDOK creates a DeleteV1ServicesServiceIDOK with default headers values
func NewDeleteV1ServicesServiceIDOK() *DeleteV1ServicesServiceIDOK {
	return &DeleteV1ServicesServiceIDOK{}
}

/*
DeleteV1ServicesServiceIDOK describes a response with status code 200, with default header values.

Deletes the service from FireHydrant.
*/
type DeleteV1ServicesServiceIDOK struct {
	Payload *models.ServiceEntity
}

// IsSuccess returns true when this delete v1 services service Id o k response has a 2xx status code
func (o *DeleteV1ServicesServiceIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete v1 services service Id o k response has a 3xx status code
func (o *DeleteV1ServicesServiceIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete v1 services service Id o k response has a 4xx status code
func (o *DeleteV1ServicesServiceIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete v1 services service Id o k response has a 5xx status code
func (o *DeleteV1ServicesServiceIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete v1 services service Id o k response a status code equal to that given
func (o *DeleteV1ServicesServiceIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteV1ServicesServiceIDOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/services/{service_id}][%d] deleteV1ServicesServiceIdOK  %+v", 200, o.Payload)
}

func (o *DeleteV1ServicesServiceIDOK) String() string {
	return fmt.Sprintf("[DELETE /v1/services/{service_id}][%d] deleteV1ServicesServiceIdOK  %+v", 200, o.Payload)
}

func (o *DeleteV1ServicesServiceIDOK) GetPayload() *models.ServiceEntity {
	return o.Payload
}

func (o *DeleteV1ServicesServiceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
