// Code generated by go-swagger; DO NOT EDIT.

package post_mortems

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// PostV1PostMortemsReportsReader is a Reader for the PostV1PostMortemsReports structure.
type PostV1PostMortemsReportsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1PostMortemsReportsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostV1PostMortemsReportsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostV1PostMortemsReportsCreated creates a PostV1PostMortemsReportsCreated with default headers values
func NewPostV1PostMortemsReportsCreated() *PostV1PostMortemsReportsCreated {
	return &PostV1PostMortemsReportsCreated{}
}

/*
PostV1PostMortemsReportsCreated describes a response with status code 201, with default header values.

Create a report
*/
type PostV1PostMortemsReportsCreated struct {
	Payload *models.PostMortemsPostMortemReportEntity
}

// IsSuccess returns true when this post v1 post mortems reports created response has a 2xx status code
func (o *PostV1PostMortemsReportsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 post mortems reports created response has a 3xx status code
func (o *PostV1PostMortemsReportsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 post mortems reports created response has a 4xx status code
func (o *PostV1PostMortemsReportsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 post mortems reports created response has a 5xx status code
func (o *PostV1PostMortemsReportsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 post mortems reports created response a status code equal to that given
func (o *PostV1PostMortemsReportsCreated) IsCode(code int) bool {
	return code == 201
}

func (o *PostV1PostMortemsReportsCreated) Error() string {
	return fmt.Sprintf("[POST /v1/post_mortems/reports][%d] postV1PostMortemsReportsCreated  %+v", 201, o.Payload)
}

func (o *PostV1PostMortemsReportsCreated) String() string {
	return fmt.Sprintf("[POST /v1/post_mortems/reports][%d] postV1PostMortemsReportsCreated  %+v", 201, o.Payload)
}

func (o *PostV1PostMortemsReportsCreated) GetPayload() *models.PostMortemsPostMortemReportEntity {
	return o.Payload
}

func (o *PostV1PostMortemsReportsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostMortemsPostMortemReportEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
