// Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/firehydrant/api-client-go/models"
)

// GetV1ReportsMeanTimeReader is a Reader for the GetV1ReportsMeanTime structure.
type GetV1ReportsMeanTimeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ReportsMeanTimeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1ReportsMeanTimeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/reports/mean_time] getV1ReportsMeanTime", response, response.Code())
	}
}

// NewGetV1ReportsMeanTimeOK creates a GetV1ReportsMeanTimeOK with default headers values
func NewGetV1ReportsMeanTimeOK() *GetV1ReportsMeanTimeOK {
	return &GetV1ReportsMeanTimeOK{}
}

/*
GetV1ReportsMeanTimeOK describes a response with status code 200, with default header values.

Returns a report with time bucketed analytics data
*/
type GetV1ReportsMeanTimeOK struct {
	Payload *models.ReportEntity
}

// IsSuccess returns true when this get v1 reports mean time o k response has a 2xx status code
func (o *GetV1ReportsMeanTimeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get v1 reports mean time o k response has a 3xx status code
func (o *GetV1ReportsMeanTimeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get v1 reports mean time o k response has a 4xx status code
func (o *GetV1ReportsMeanTimeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get v1 reports mean time o k response has a 5xx status code
func (o *GetV1ReportsMeanTimeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get v1 reports mean time o k response a status code equal to that given
func (o *GetV1ReportsMeanTimeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get v1 reports mean time o k response
func (o *GetV1ReportsMeanTimeOK) Code() int {
	return 200
}

func (o *GetV1ReportsMeanTimeOK) Error() string {
	return fmt.Sprintf("[GET /v1/reports/mean_time][%d] getV1ReportsMeanTimeOK  %+v", 200, o.Payload)
}

func (o *GetV1ReportsMeanTimeOK) String() string {
	return fmt.Sprintf("[GET /v1/reports/mean_time][%d] getV1ReportsMeanTimeOK  %+v", 200, o.Payload)
}

func (o *GetV1ReportsMeanTimeOK) GetPayload() *models.ReportEntity {
	return o.Payload
}

func (o *GetV1ReportsMeanTimeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReportEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
