// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NuncComponentEntity nunc component entity
//
// swagger:model NuncComponentEntity
type NuncComponentEntity struct {

	// component group id
	ComponentGroupID string `json:"component_group_id,omitempty"`

	// infrastructure id
	InfrastructureID string `json:"infrastructure_id,omitempty"`

	// infrastructure type
	InfrastructureType string `json:"infrastructure_type,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// position
	Position int32 `json:"position,omitempty"`
}

// Validate validates this nunc component entity
func (m *NuncComponentEntity) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this nunc component entity based on context it is used
func (m *NuncComponentEntity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NuncComponentEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NuncComponentEntity) UnmarshalBinary(b []byte) error {
	var res NuncComponentEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
