// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostV1IncidentsIncidentIDTasksTaskIDConvert Convert a task to a follow-up
//
// swagger:model postV1IncidentsIncidentIdTasksTaskIdConvert
type PostV1IncidentsIncidentIDTasksTaskIDConvert struct {

	// description
	Description string `json:"description,omitempty"`

	// project id
	ProjectID string `json:"project_id,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// summary
	Summary string `json:"summary,omitempty"`

	// List of tags for the ticket
	TagList []string `json:"tag_list"`
}

// Validate validates this post v1 incidents incident Id tasks task Id convert
func (m *PostV1IncidentsIncidentIDTasksTaskIDConvert) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post v1 incidents incident Id tasks task Id convert based on context it is used
func (m *PostV1IncidentsIncidentIDTasksTaskIDConvert) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostV1IncidentsIncidentIDTasksTaskIDConvert) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostV1IncidentsIncidentIDTasksTaskIDConvert) UnmarshalBinary(b []byte) error {
	var res PostV1IncidentsIncidentIDTasksTaskIDConvert
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
