// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostV1SeverityMatrixImpacts Create a new impact
//
// swagger:model postV1SeverityMatrixImpacts
type PostV1SeverityMatrixImpacts struct {

	// affects id
	// Required: true
	AffectsID *string `json:"affects_id"`

	// affects type
	// Required: true
	AffectsType *string `json:"affects_type"`

	// position
	Position int32 `json:"position,omitempty"`
}

// Validate validates this post v1 severity matrix impacts
func (m *PostV1SeverityMatrixImpacts) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAffectsID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAffectsType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostV1SeverityMatrixImpacts) validateAffectsID(formats strfmt.Registry) error {

	if err := validate.Required("affects_id", "body", m.AffectsID); err != nil {
		return err
	}

	return nil
}

func (m *PostV1SeverityMatrixImpacts) validateAffectsType(formats strfmt.Registry) error {

	if err := validate.Required("affects_type", "body", m.AffectsType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post v1 severity matrix impacts based on context it is used
func (m *PostV1SeverityMatrixImpacts) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostV1SeverityMatrixImpacts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostV1SeverityMatrixImpacts) UnmarshalBinary(b []byte) error {
	var res PostV1SeverityMatrixImpacts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
