// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectConfigEntity Retrieve configuration for a ticketing project
//
// swagger:model ProjectConfigEntity
type ProjectConfigEntity struct {

	// connection id
	ConnectionID string `json:"connection_id,omitempty"`

	// connection type
	ConnectionType string `json:"connection_type,omitempty"`

	// details
	Details string `json:"details,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// ticketing project id
	TicketingProjectID string `json:"ticketing_project_id,omitempty"`
}

// Validate validates this project config entity
func (m *ProjectConfigEntity) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this project config entity based on context it is used
func (m *ProjectConfigEntity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectConfigEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectConfigEntity) UnmarshalBinary(b []byte) error {
	var res ProjectConfigEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
