// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReadinessCheckEntity readiness check entity
//
// swagger:model ReadinessCheckEntity
type ReadinessCheckEntity struct {

	// content
	Content string `json:"content,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// documentation link
	DocumentationLink string `json:"documentation_link,omitempty"`

	// link
	Link string `json:"link,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// ok
	Ok string `json:"ok,omitempty"`

	// required
	Required string `json:"required,omitempty"`
}

// Validate validates this readiness check entity
func (m *ReadinessCheckEntity) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this readiness check entity based on context it is used
func (m *ReadinessCheckEntity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReadinessCheckEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReadinessCheckEntity) UnmarshalBinary(b []byte) error {
	var res ReadinessCheckEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
